### ISSUE TITLE
External user defined identifiers are matched against the Norm

### ISSUE THREAD

**Issue by Neirpyc** [42School/norminette#10]
For example, using `XK_Escape` from `X11/keysym.h` causes:
```
	FORBIDDEN_CHAR_NAME  (line: **, col: **):	user defined identifiers should contain only lowercase characters, digits or '_'
```

**Comment by N0ich** [comment]
I'm all out of ideas for this. 

I'll try to figure something out or simply remove the lowercase check.

**Comment by Neirpyc** [comment]
Maybe only check at define time and not use time?

**Comment by N0ich** [comment]
Removed the verification in next update until we have a better, permanent solution. Can't dissociate external symbols and internal symbols without compiling unfortunately.
