### ISSUE TITLE
Condition without brackets indent problem

### ISSUE THREAD

**Issue by LoisDuplain** [42School/norminette#102]
**Describe the bug**
Yes it works correctly and compile correctly:
[http://www.noelshack.com/2021-12-2-1616497276-screen-shot-2021-03-23-at-11-38-51-am.png](http://www.noelshack.com/2021-12-2-1616497276-screen-shot-2021-03-23-at-11-38-51-am.png)
But the actually the norm want it:
[http://www.noelshack.com/2021-12-2-1616497276-screen-shot-2021-03-23-at-11-39-06-am.png](http://www.noelshack.com/2021-12-2-1616497276-screen-shot-2021-03-23-at-11-39-06-am.png)

The norm pdf specify nothing for that case.

**Comment by N0ich** [comment]
The pdf is updated and will be on the intra soon. I apologize for the delay
