### ISSUE TITLE
Cannot use error directive

### ISSUE THREAD

**Issue by vincentvis** [42School/norminette#103]
**Describe the bug**
I use `ifndef` to check if some variable is set during compilation,
if not I throw an error, but this gives the following norm error:
`PREPROC_UKN_STATEMENT (line:  16, col:   1):	Unrecognized preprocessor statement`

**Erroneous code**
```c
# ifndef LIBFT_H
#  error "Never include "ft_nbr.h" directly; use "libft.h" instead."
# endif
```

**Additional infos**
 - OS: macos 10.14.6
 - python --version: 3.9.1
 - norminette -v: 3.2.3

**Comment by mjy9088** [comment]
I'm having the same problem too.

I can't support Windows because of this

```c
#ifndef PRELUDE_WARNING_4200_H
# define PRELUDE_WARNING_4200_H

# ifdef _MSC_VER
#  pragma warning(disable: 4200)
# endif

#endif
```
