### ISSUE TITLE
Pointer to function declarations not recognized properly

### ISSUE THREAD

**Issue by bororama** [42School/norminette#108]
Norminette doesn't seem to recognize pointer-to-function declarations as declarations.
The following code snippet is formatted according to the norm
```
int	main(void)
{
	int		ret;
	int		(*f)(int, int);

	f = sum_2_ints;
	return (f(2, 3));
}
```
But it outputs
> main.c: KO!
	NL_AFTER_VAR_DECL    (line:  13, col:   1):	Variable declarations must be followed by a newline
	TAB_INSTEAD_SPC      (line:  13, col:   9):	Found tab when expecting space
	EMPTY_LINE_FUNCTION  (line:  14, col:   1):	Empty line in function

Yet the erroneously formatted
```
int	main(void)
{
	int		ret;

	int (*f)(int, int);
	f = sum_2_ints;
	return (f(2, 3));
}
```
Actually passes with an `OK!`

 _norminette 3.1.2_

**Comment by N0ich** [comment]
Hello, your norminette is not up to date, this has been fixed in a previous issue.
Closing since I dont have the issue on the live version.
