### ISSUE TITLE
(at least) enum identifiers not being enforced by unixcase / snake case rule

### ISSUE THREAD

**Issue by mmirabetti** [42School/norminette#111]
**Describe the bug**
(at least) enum identifiers accepting upper case characters

**Erroneous code**
`enum	e_resultCodes	{`
	`C3D_OK`
`};`

`➜  include git:(master) ✗ norminettev2 c3d_error.h`
`Norme: ./c3d_error.h`
`Error (line 37, col 0): e_resultCodes not unixcase`

`➜  include git:(master) ✗ norminette c3d_error.h` 
`c3d_error.h: OK!`

**Additional infos**

 - OS: Ubuntu 20.04 (Focal Fossa)
 - python --version: Python 3.9.0
 - norminette -v: norminette 3.2.5

**Comment by N0ich** [comment]
Hello,
This is expected for now. Librairies such as mlx contains identifiers which do not respect the norm, so i've disabled the check on this.
