### ISSUE TITLE
Inconsistent SPC_BFR_PAR behaviour

### ISSUE THREAD

**Issue by fifididi** [42School/norminette#112]
**Describe the bug**
The behaviour of the SPC_BFR_PAR rule is inconsistent.

**Erroneous code**
```c
#include <stdio.h>

int	main(void)
{
	const char	*s = "01";

	printf("%c\n", s[1]);
	printf("%c\n", "01"[1]);
	printf("%c\n", 1["01"]);
}
```

**Additional infos**
 - python --version: `Python 3.8.5`
 - norminette -v: `norminette 3.2.5`

**Additional context**
The first call to printf passes the norm while the other two trigger a norm error. While I agree the third case is a little bit unconventional, I see no reason for the second case to be considered an error.

**Comment by N0ich** [comment]
Closed in 518fdda06eae6e748129f334b8925cdc1add8fcd
