### ISSUE TITLE
Norm error on pointer to function array

### ISSUE THREAD

**Issue by Anloubie42** [42School/norminette#114]
**Describe the bug**
I tried to create a pointer to function array inside of a struct, and the norm gives me an error I shouldn't have.

**Erroneous code**

The declaration resulting in a norm error :

`void			    (*op[11])(struct s_infos *infos);`

The norm error I get :

`EXP_PARENTHESIS      (line: 41, col: 25):	Expected parenthesis`

The col 25 should be the first closing perenthesis 

**Additional infos**
 - OS: MacOS bigSur v. 11.2.1
 - python --version: 2.7.16
 - python3 --version: 3.8.2
 - norminette -v: norminette 2.52

**Additional context**

this declaration is inside the declaration of the struct s_infos. I think there is a link.

<img width="713" alt="Capture d’écran 2021-03-30 à 00 26 07" src="https://user-images.githubusercontent.com/56688817/113027266-2a87f680-918a-11eb-88a7-4297a81a8bd7.png">
<img width="603" alt="Capture d’écran 2021-03-30 à 12 11 50" src="https://user-images.githubusercontent.com/56688817/113027281-2e1b7d80-918a-11eb-9eaa-20b859a0ca1b.png">

**Comment by N0ich** [comment]
Hello,
This has been been fixed with norminette 3.x, you are still running 2.5.2.
Please update the norminette
