### ISSUE TITLE
Casting error, minus-sign mistaken for an operator.

### ISSUE THREAD

**Issue by JayBeest** [42School/norminette#115]
**Describe the bug**
When trying to pass my code through Norminette i receive faulty errors.
It happens when casting -1 as size_t. I get the following errors:
SPC_AFTER_PAR        (line:  20, col:  31):	Missing space after parenthesis (brace/bracket)
SPC_AFTER_OPERATOR   (line:  20, col:  32):	missing space after operator

**Erroneous code**
```c
#include <stdio.h>

int	main(void)
{
	size_t	i;
	int		num;

	i = (size_t)-1;
	printf("%zu\n", i);
	num = (int)i;
	num = (int) i;
	return (0);
}

```

**Additional infos**
 - OS: macOS Big Sur 11.2.3
 - python --version: Python 2.7.16 / Python 3.9.2
 - norminette -v: norminette 3.2.3 (edit - 3.2.6)

**Additional context**
I also remember stumbling upon some arbitrary rule for casting in general (see casting 'i' as an int).
Maybe this has something to do with it?

P.S. just now also tested with 3.2.6, same issue.

**Comment by Gontjarow** [comment]
This also happens with dereferencing.
```
Error: SPC_AFTER_OPERATOR   (line:  25, col:  27)
>   if (flag->p > (size_t)*len)
```
As well as the bitwise NOT `~` operator.
```
Error: SPC_AFTER_OPERATOR   (line:  96, col:  42)
>   if (flag->bit & FLAG_LEADING_ZERO && ~flag->precision)
```
