### ISSUE TITLE
Splitting string literal

### ISSUE THREAD

**Issue by celomary** [42School/norminette#116]
cannot split string literal into lines using a backslash, the norm just keeps increasing the cols counter of the first line by one.

**Comment by libre-hackerman** [comment]
Have you tried splitting the literal by just putting it in several literals together?
Like this:
```
#include <stdio.h>

int     main(void)
{
        printf("Hello "
                        "world\n");
        return (0);
}
```

**Comment by celomary** [comment]
I think it works that way, if you don't mind can you add this case to the norm pdf just to let other students know, thank u
