### ISSUE TITLE
Incorrect extra tabs before function name

### ISSUE THREAD

**Issue by Gontjarow** [42School/norminette#118]
**Describe the bug**

`ft_printf.c: Error!`
`Error: TOO_MANY_TABS_FUNC   (line:  75, col:   9):      extra tabs before function name`
![ft_printf](https://user-images.githubusercontent.com/54755292/113494073-cb114a00-94ed-11eb-9e93-7a378ad3b98f.png)

`ft_printf.c: OK!`
![ft_printf-ok](https://user-images.githubusercontent.com/54755292/113494126-2d6a4a80-94ee-11eb-8280-09922c1091ee.png)

**Additional infos**
 - OS: Linux (Github Codespaces)
 - python --version: Python 3.8.6
 - norminette -v: norminette 3.2.6

**Additional context**
Here is a file where the error occurs:
https://github.com/Gontjarow/Hive_printf/blob/fecedb6ce591450f925b77e2b3862d6c726bc5cf/ft_printf.c

**Comment by SimonCROS** [comment]
This is not a bug, it is no longer like in the norm v2 where we had to align everything.

> Each function must have a single tabulation between its return type and its name.

**Comment by Gontjarow** [comment]
Oh okay, seems like I misunderstood the new rules. Thanks!
