### ISSUE TITLE
Variables, functions and files names are not checked

### ISSUE THREAD

**Issue by SimonCROS** [42School/norminette#119]
**Describe the bug**
According to the PDF, variables, functions and files names must use the "snake case", but it's never tested by the norminette.

**Erroneous code**
```c
int	hEy(int Hey, int hEy, int heY)
{
	int	Hey2;
	int	hEy2;
	int	heY2;
}
```
`hEy.c: OK!`

---

**Additional infos**
 - OS: Ubuntu 20.04.2 LTS (WSL 2)
 - python --version: 3.8.5
 - norminette -v: 3.2.6

**Additional context**
These sentences in the PDF describe the same things with different words.
> Variables and functions names can only contain lowercases, digits and '\_' (Unix Case).
> Files and directories names can only contain lowercases, digits and '\_' (Unix Case).

> Variables, functions, and any other identifier must use snake case. No capital letters, and each word separated by an underscore.

**Comment by N0ich** [comment]
Hello,

This has been removed from the checks themselves for now, due to the way it is checked for stuff like the mlx, which contains camel case function names. 
We will work on a better solution
