### ISSUE TITLE
Wrong detection of bad indentation in a certain case

### ISSUE THREAD

**Issue by 2LeoCode** [42School/norminette#121]
**Describe the bug**
When we put a `if` - `else` statement inside a `while` statement without opening and closing brackets, the norm detects a wrong tab indentation but the indentation is not wrong.

**Erroneous code**
```
1   int main(void)
2   {
3       while (1)
4           if (1)
5               continue ;
6           else
7               continue ;
8   }
```
norminette outputs:
```
Error: TOO_MANY_TAB         (line:   6, col:   1):	Extra tabs for indent level
Error: TOO_MANY_TAB         (line:   7, col:   1): Extra tabs for indent level
```
But with
```
1   int main(void)
2   {
3       while (1)
4           if (1)
5               continue ;
6       else
7           continue ;
8   }
```
norminette is good, but it should be an indentation error

**Additional infos**
 - OS: mac-OS
 - python --version: Python 2.7.16
 - norminette -v: norminette 3.2.6

**Additional context**

**Comment by N0ich** [comment]
Hello and thank you for your ticket.
This is expected. Each loop/condition without braces can only have a single condition/loop/line inside.
Since you have 2 conditionals in your loop, norminette expects it to have braces.

**Comment by 2LeoCode** [comment]
Okay, if so, the second example shouldn't work, but it works because the else is wrongly indented, so the norminette fails to detect it because it thinks it's outside the `while` loop
