### ISSUE TITLE
Issue the code example in the pdfs doesn't pass the Norm.

### ISSUE THREAD

**Issue by monoue** [42School/norminette#126]
**Describe the bug**
The code example in the pdfs (English, French and Brazilian Portuguese) doesn't pass the Norm, because the variables are not aligned.
The said example is in the fifth section ("Headers" in English version).

**Erroneous code**
```
#ifndef FT_HEADER_H
# define FT_HEADER_H
# include <stdlib.h>
# include <stdio.h>
# define FOO "bar"

int g_variable;   // These two are not aligned.
struct s_struct;

#endif
```

**Comment by N0ich** [comment]
Thank you, i've fixed it.
