### ISSUE TITLE
Error: TOO_MANY_VALS        (line:  X1, col:  X2):      Too many values on define

### ISSUE THREAD

**Issue by madvid** [42School/norminette#127]
**Describe the bug**
Error is raised despite the rules in the pdf. The error concerned macros define based on previous macros.
```bash
Error: TOO_MANY_VALS        (line:  19, col:  31):      Too many values on define
Error: TOO_MANY_VALS        (line:  19, col:  38):      Too many values on define
Error: TOO_MANY_VALS        (line:  20, col:  34):      Too many values on define
Error: TOO_MANY_VALS        (line:  21, col:  32):      Too many values on define
Error: TOO_MANY_VALS        (line:  21, col:  39):      Too many values on define
Error: TOO_MANY_VALS        (line:  22, col:  35):      Too many values on define
Error: TOO_MANY_VALS        (line:  22, col:  42):      Too many values on define
Error: TOO_MANY_VALS        (line:  23, col:  37):      Too many values on define
```

Based on what it is written in the pdf:
![image](https://user-images.githubusercontent.com/37487348/114077590-45ecb300-98a8-11eb-9f78-41da115b72f3.png)
strictly speaking a constant plus, minus, divided (except if it is 0), multiply by another constant is a constant.

**Erroneous code**
Here the code which lead to the errors.
```C
# define W_LX 500
# define W_LY 500
# define IMG_LX W_LX
# define IMG_LY 9 * W_LY / 10
# define TXT_Y W_LY / 10
# define MD_X 90 * W_LX / 100
# define FCL_X 40 *  W_LX / 50
# define HLP_X W_LX / 100
```

**Additional infos**
 - OS: Ubuntu 20.04.2 LTS
 - python --version: 3.7.3
 - norminette -v: 3.2.6

**Additional context**
not relevant

**Comment by N0ich** [comment]
Hello, 
As specified in #12, using operators on define is for now not allowed.
Sorry for the inconvenience.
