### ISSUE TITLE
Preprocessors and empty lines above functions are not consistent

### ISSUE THREAD

**Issue by pajotg** [42School/norminette#129]
**Describe the bug**
When adding a `#ifdef` / `#else` combo to a function since it differs a bit on linux/mac
I noticed that it complained on the `#else` about `NEWLINE_PRECEDES_FUNC`  but it did not on the `#ifdef`

**Erroneous code**
```
#ifdef OS_Linux
static void	hook_events(t_mlx_data *mlx_data)
{
}
#else
static void	hook_events(t_mlx_data *mlx_data)
{
}
#endif
```

**Additional infos**
 - OS: GNU/Linux
 - python --version: Python 2.7.18 (also have 3.8.5 and 3.9.2)
 - norminette -v: 3.2.7

**Additional context**
Nothing really

**Comment by N0ich** [comment]
Hello,

It's behaving properly. You dont need a newline on the first function of the file. Adding a function above will prompt the NEWLINE_PRECEDES_FUNC error on the first function aswell.
Thank you for your issue.
