### ISSUE TITLE
`restrict` keyword is not handled by norminette

### ISSUE THREAD

**Issue by 2LeoCode** [42School/norminette#131]
**Describe the bug**
There are two problems that I've noticed while trying to use the `restrict` keyword:
- When used inside a function prototype like, we get:
```
Error: MISSING_IDENTIFIER   (line:  xxx, col:  xxx):	missing type qualifier or identifier in function arguments
```

- When used with a declared variable it works but it detects an extraneous empty-line after the variable, so for the norminette to display OK we need to not have an empty-line after the declaration.

I didn't see in the norm that this keyword is forbidden, so I'm assuming it's not handled by the norminette.

**Erroneous code**

1. 

```
1 void    foo(const char *restrict s)
2 {
3   (void)s;
4 }
```
Output:
```
Error: MISSING_IDENTIFIER   (line:  1, col:  24):	missing type qualifier or identifier in function arguments
```

2.
```
1 #include <stdio.h>
2
3 int main(void)
4 {
5     const char *restrict s = "Hello World";
6
7     printf("%s\n", s);
8     return (0);
9 }
```
Output:
```
Error: EMPTY_LINE_FUNCTION  (line:  6, col:   1):	Empty line in function
```

And without the empty line at line 6 the output is:
```
main.c: OK!
```
But we should need an empty line after declarations so this one should be wrong

**Additional infos**
 - OS: Mac-OS Catalina 10.15.7
 - python --version: Python 2.7.16
 - python3 --version: Python 3.9.1
 - norminette -v: norminette 3.2.6

**Additional context**

**Comment by N0ich** [comment]
Hello,
I believe this is not in the norminette's current scope, since restrict isn't used by the school C standard.
I'm deploying a fix anyway, but it's not optimal.

Thanks for the issue.
