### ISSUE TITLE
extra tabs in condition

### ISSUE THREAD

**Issue by antikostya** [42School/norminette#136]
if you write a single-line conditional statement in the indent - norminette thinks that only first branch should have indentation
in this code 
```c
int	main(void)
{
  int a;

  while (1)
    if (a)
      a++;
    else
      a--;
}
```
you will get message
```
Error: TOO_MANY_TAB         (line:  8, col:   1):	Extra tabs for indent level
Error: TOO_MANY_TAB         (line:  9, col:   1):	Extra tabs for indent level
```
and this solve issue:
```c
int	main(void)
{
  int a;

  while (1)
    if (a)
      a++;
  else
    a--;
}
```
**Additional infos**
 - OS: linux mint 20
 - python --version: Python 3.8.5
 - norminette -v: norminette 3.2.8

**Comment by N0ich** [comment]
This is expected and described in the pdf. The norm expects only one inline condition when not using brackets.
