### ISSUE TITLE
Incorrect variable declaration type checking

### ISSUE THREAD

**Issue by x33nu** [42School/norminette#142]
**Describe the bug**
Latest norminette incorrectly handles declarations of unsigned variables and consecutively doesn't consider such lines as variable declarations.

**Erroneous code**
```
#include <stdio.h>

int main(void)
{
    unsigned    n;

    n = 42;
    printf("%u\n", n);
}
```

norminette output:

```
test.c: Error!
Error: IMPLICIT_VAR_TYPE    (line:   5, col:   1):	Missing type in variable declaration
Error: CONSECUTIVE_NEWLINES (line:   6, col:   1):	Consecutive newlines
Error: EMPTY_LINE_FUNCTION  (line:   6, col:   1):	Empty line in function
```

**Additional infos**
 - OS: macOS Mojave 10.14.6
 - python --version: 3.7.8, 3.8.5
 - norminette -v: 3.2.95

**Comment by x33nu** [comment]
```
union u_extended
{
	long double				value;
	struct
	{
		unsigned long long	mantissa : 64;
		unsigned			exponent : 15;
		unsigned			sign : 1;
	}						s_;
};
```

Although this code gives no error (maybe because of anonymous struct).

**Comment by x33nu** [comment]
```
void	bigint_power_of_five(t_bigint *this, unsigned power);
```

And this one still produces error.

**Comment by N0ich** [comment]
Hello, implicit variable types aren't allowed in the norminette for now.

Thank you for your report
