### ISSUE TITLE
Issue with if-else without brackets within while without brackets

### ISSUE THREAD

**Issue by bemayer** [42School/norminette#144]
**Describe the bug**
The Norminette reports an error for an *if-else* structure without brackets within a *while* without brackets if the *else* is indented on the same level as the *if*, but not if it is on the same level as the *while*.

**Erroneous code**

***Test.c***

```c
int	main(void)
{
	while (1)
		if (0)
			return (1);
	else
		return (0);
	return (1);
}
```

***Norminette***

```
test.c: OK!
```

***Test2.c***

```c
int	main(void)
{
	while (1)
		if (0)
			return (1);
		else
			return (0);
	return (1);
}
```

***Norminette***

```
test2.c: Error!
Error: TOO_MANY_TAB         (line:  18, col:   1):	Extra tabs for indent level
Error: TOO_MANY_TAB         (line:  19, col:   1):	Extra tabs for indent level
```

**Comment by N0ich** [comment]
Hello,
As said in the other issues about this specific problem, this is expected. You can only nest one condition in a condition without brackets.

**Comment by bemayer** [comment]
Hello,
I did expected my test.c example to produce an error, my issue is that it does not.

**Comment by N0ich** [comment]
Hello,
Test 1 is a pure C error (else not preceded by if) this is not the norminette job to underline this problem.
Keeping this issue closed, thank you !

**Comment by bemayer** [comment]
It compiles, but nevermind.
Thank you for your answer!
