### ISSUE TITLE
Wrongly detected "TOO_MANY_TAB"

### ISSUE THREAD

**Issue by fletcher97** [42School/norminette#149]
**Describe the bug**
Norminette is declaring a correct file as wrong saying a line has too many line if an `else` statement is present inside a block that doesn't have brackets (i.e: If a loop has only the `if-else` statement and no brackets are placed the `else` part is flagged for TOO_MANY_TAB).

**Erroneous code**
```
void	ft_stackdestroy(t_stack *stack, void (*del)(void *))
{
	while (ft_stacksize(stack))
		if (del)
			del(ft_stackpop(stack));
		else
			ft_stackpop(stack);
	ft_free(stack);
}
```
Output:
```
Error: TOO_MANY_TAB         (line:  X, col:   1):      Extra tabs for indent level
```

**Additional infos**
 - OS:  `Ubuntu 18.04.5 LTS` running on `5.4.72-microsoft-standard-WSL2`
 - Python: `3.9.4`
 - Norminette: `3.2.95`

**Comment by N0ich** [comment]
Hello, 
if-else statements in an unbracketed control structure are not allowed by the norminette as far as it's been designed for now.
