### ISSUE TITLE
misleading error message when missing brackets.

### ISSUE THREAD

**Issue by loukeendub** [42School/norminette#150]
**Describe the bug**

[Error: MULT_IN_SINGLE_INSTR (line:  21, col:   1):      Multiple instructions in single line control structure]

this was shown when norminette detected missing brackets in an if-statement with a while in it. The while itself has brackets and multiple lines of comands (see function below)

-----------------------
[ERRONEOUS CODE]
void	ft_lstclear(t_list **lst, void (*del)(void *))
{
	t_list	*p;

	if (lst && del)
		while (*lst)
		{
			p = (*lst)->next;
			del((*lst)->content);
			free(*lst);
			*lst = p;
		}
	*lst = NULL;
}
---------------------
[APPROVED CODE]
void	ft_lstclear(t_list **lst, void (*del)(void *))
{
	t_list	*p;

	if (lst && del)
	{
		while (*lst)
		{
			p = (*lst)->next;
			del((*lst)->content);
			free(*lst);
			*lst = p;
		}
	}
	*lst = NULL;
}
--------------------

**Additional infos**
 - norminette V3

**Additional context**

**Comment by N0ich** [comment]
Hello,
For now, multi-line conditions must be bracketed (as expected by C language) and control structure that include multi-line control structures must be bracketed as well, which is why the second code is valid while the first isn't. 

Thank you for you report.
