### ISSUE TITLE
Uppercase letters in variable, function and file names are not reported as an error

### ISSUE THREAD

**Issue by JonathanDUFOUR** [42School/norminette#151]
```C
void	MyFunc(void)
{
	(void);
}

int	main(void)
{
	int	A;
}
```
```shell
norminette
MAIN.c: OK!
```
Expected result would be an error caused by the uppercase letters in names.
As the norme says, at chapter II.1

- Variables and functions names can only contain **lowercases**, digits and ’_’ (UnixCase).
- Files and directories names can only contain **lowercases**, digits and ’_’ (Unix Case).

**Comment by N0ich** [comment]
Hello, 
unfortunately we cannot report them as error for now, as capital letters are used in various cases where the norminette is required, such as mlx, which would then count as error. The code exists but is disabled until we find a better solution. 

Thank you for your report
