### ISSUE TITLE
Dockerfile using python:3.7

### ISSUE THREAD

**Issue by Tawliew** [42School/norminette#152]
**"Describe the bug"**
Hello! I'm sorry to open this issue as a bug type, but I can't find the correct one. I have a suggestion to make in the Dockerfile.

Currently, the Dockerfile is using `python:3.7` image. `python:3.7` image has ~ **900MB**, which is a considerable space. It's common in the container world to use **[alpine](https://www.alpinelinux.org/about/)** images when using one app inside a container. 

**Python has an alpine tag**: `python:3.7-alpine`. I've tried to use norminette running inside `python:3.7-alpine` and, so far, I didn't have any errors. Using this tag will allow us to shrink the size of the container to ~ **70MB**.

Could I make a PR to change this line in Dockerfile:
 `FROM python:3.7` 
To this line
`FROM python:3.7-alpine`

Thanks for your time!

**Additional infos**
 - OS: Pop!_OS 20.10 x86_64
 - python --version: 3.7.10
 - norminette -v: 3.3.0

**Comment by N0ich** [comment]
Hello, great idea. 
I didn't handle the docker port so feel free to do a PR :)

Thank you
