### ISSUE TITLE
Prefix increment/decrement not recognized

### ISSUE THREAD

**Issue by vincentvis** [42School/norminette#155]
**Describe the bug**
Prefix increment/decrement operators are compound assignments, according to ISO/IEC 9899.

> The value of the operand of the prefix `++` operator is incremented.  The result is the new value of the operand after incrementation. The expression `++E` is equivalent to (`E+=1`).

The `E += 1` variety is correctly identified as not norm, but `++E` is missed, and should be added, since they are equivalent.

Reference (bottom of page 76, section _6.5.3.1 Prefix increment and decrement operators_):
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2310.pdf#page=76
(same thing is mentioned in the [1999 version](http://www.dii.uchile.cl/~daespino/files/Iso_C_1999_definition.pdf), if the one linked earlier is to recent)

**Erroneous code**
```c
#include <stdio.h>

int	main(void)
{
	int	i;

	i = 0;
	while (++i < 10)
	{
		printf("in ++i loop %i\n", i);
	}
	while ((i += 1) < 20)
	{
		printf("in i+=1 loop %i\n", i);
	}
	return (0);
}
```

**Additional info**
 - OS: macos
 - python --version: 3.9.1
 - norminette -v: 3.3.0

**Comment by N0ich** [comment]
Hello,
Thank you for your issue. 
This is intended. Assigns in control are no longer authorized, however we wanted to give a slight leeway to the students by allowing them to increment/decrement stuff in their control structure to facilitate the 25 lines rule.
+= and -= behave differently as they allow you to put in any value (not only 1) and thus could be used to bypass the norm.
Closing this issue

**Comment by vincentvis** [comment]
As the expression `++E` is equivalent to `(E+=1)` (and not even by opinion, but by C language spec). 
Should you then also allow `E+=1`? or `E+=x` as long as `x` equals 1?

Or is this a special exception, where if you write it as either `++E` or `E++` it is allowed, but the equivalence of `++E`, `E+=` is _not_ allowed?

By allowing `++E` and `E++` you can still increment more than one by just chaining them comma separated, which does not cause a norm error, is this also fine according to the norm?
```c
while ((i++, i++, i++, i++, i++) < 100)
    printf("multiples of 5 below 101: %i\n", i);
```

**Comment by paulo-santana** [comment]
The equivalence of the two operations is on the field of semantics, rather than in the field of syntax. While, yes, they both result in the same output, they still are two different operations and create two different set of assembly instructions (`lea` for `i++`, `add` for `i += 1`.

This, tho
```c
while ((i++, i++, i++, i++, i++) < 100)
    printf("multiples of 5 below 101: %i\n", i);
```
results in four consecutive `add` instructions, followed by a `lea` instruction. Therefore, I agree it should be treated as a norm violation of the "one instruction in one line" constraint. It's a bug rather than an intended feature.

**Comment by N0ich** [comment]
Hello,

Please refrain from calling "bugs" features you don't agree with. While both of your arguments stand, the chosen way of allowing students to increment a variable within a control structure will stay. 
`Or is this a special exception, where if you write it as either ++E or E++ it is allowed, but the equivalence of ++E, E+= is not allowed?` : yes, as said in my first post, this is an exceptional exception.
I'd also like to remind you that this is a bug report feature. I am not in charge of deciding whether such or such concept should be in the norm.

Have a good day

**Comment by paulo-santana** [comment]
Well, thank you for confirming it is a feature, then;
