### ISSUE TITLE
Using typedef on external structs

### ISSUE THREAD

**Issue by wendrul** [42School/norminette#156]
**Describe the bug**
When trying to use typedef to abbreviate the writing of external structs such as here:
```c
typedef struct dirent    t_dirent;
```
you get this norm error
```
Error: STRUCT_TYPE_NAMING   (line:  38, col:  16):      Structure name must start with s_
```
But there is no way of changing the name of `dirent` since it belongs to an external library.

**To reproduce this**
```c
# include <dirent.h>
typedef struct dirent    t_dirent;
```

**Additional infos**
 - OS: xubuntu virtual machine
 - python --version: `Python 3.7.5`
 - norminette -v: `norminette 3.3.0`

**Additional context**
The point of doing this is to avoid typing structs as `struct thing` which takes a lot of space in a line and makes it harder to comply with line length and function length limits established by the norme itself.

**Comment by fifididi** [comment]
Hello, to bypass this error you can use the typeof operator as follows:
`#include <dirent.h>

typedef typeof(struct dirent)  t_dirent;
...`

**Comment by wendrul** [comment]
Oh thanks a lot that is really nice to know. I'll get my minishell corrected with this now! I will keep the issue open though, as it is probably best if the norminette doesn't make you write in an odd manner just for the sake of it.
