### ISSUE TITLE
Rare bug. Confusing error Unexpected EOF line 2 when file doesn't end with a '\n'

### ISSUE THREAD

**Issue by hakaman2020** [42School/norminette#157]
**Describe the bug**
When Norminette process a file that don't end with a '\n' it will display the error ```Unexpected EOF line 2````. There are times that the user has set the editor not to add '\n' automatically at the end of the file. If the last line of the file contains no newline, but instead it ends with whitespace character like ' 'or '\t' then norminette will give this error.

**Erroneous code**
```c
int main(void)
{
}
'\t' <-- the file ends with a tab instead of a '\n' character.
```

**Additional infos**
 - OS: ubuntu
 - python --version: 3.8.6
 - norminette -v: 3.3

**Additional context**
This bug won't appear often because in general the editors will add a '\n' at the end of a file automatically unless it is told not to. But it can be a little bit confusing for people who are not aware of it. My first instinct was to look at line 2 of my c-file.

**Comment by N0ich** [comment]
Hello,

I've changed the error message to be more specific, but I can't really let the norminette run after finding this, so raise is the best solution. Will push with the next update
