### ISSUE TITLE
typedef struct indentation rule not being applied

### ISSUE THREAD

**Issue by iwillenshofer** [42School/norminette#158]
The norme requires that the name of typedef and struct must be aligned:

> _When declaring a struct, union or enum with a typedef, all indentation rules apply.
> You must align the typedef’s name with the struct/union/enum’s name._
> 

However, it is not possible to align both, as the name of the struct requires a space before it and the name of typedef requires indentation with tabs.

The following structures are being considered valid by the norminette (s_test and t_test not aligned):

```
typedef struct s_test
{
	int	test;
}				t_test;

```

```
typedef struct s_test
{
	int	test;
}t_test;
```

The following structure is considered **invalid** (s_test and t_test aligned):
```
typedef struct	s_test
{
	int	test;
}		t_test;
```
`Error: TAB_REPLACE_SPACE    (line:   4, col:  15):      Found tab when expecting space`

**Comment by N0ich** [comment]
Hello,

My apologies, the expected way to handle the typedef declaration is as follows:
```typedef struct s_test
{
	int	test;
}    t_test;
```
(Tab before the typedef name and space before the struct name)
It's the same behavior as when the definition is not included. I'm updating the norm's pdf.
Also removing the possibility to have multiple tabs before the typedef name to avoid confusion.

**Comment by N0ich** [comment]
Hello,
Commented a bit fast last time.
After backtracking a bit the discussions i had about this specific issue, here's what to say about it:
Allowed - 1 tab, multiple tabs
Mostly not possible (and thus not checked) indent of struct name and typedef name.

I believe the first intent was to have only one tab before typedef name when doing a full definition (just like when declaring it) 
but for compatibility issue we had to give the possibility to have multiple tabs.
I'm gonna leave it as is, and update the norm PDF.
Thank you for your issue.
