### ISSUE TITLE
`environ` global variable

### ISSUE THREAD

**Issue by leeoocca** [42School/norminette#161]
**Describe the bug**
One can't declare the variable `extern char **environ` as a global variable.

You can declare it as a local/automatic variable, but it's not as convenient. Its use is very similar to the one of `extern int errno`, except `errno` is usally included with an header (`#include <sys/errno.h>`) so you don't have this problem.

I know you receive `environ` as third argument in the `main` function, but AFAIK it's not POSIX compliant.

**Erroneous code**
```c
extern char	**environ;
```
in a `.c` or `.h` file will get you

```sh
Error: GLOBAL_VAR_NAMING    (line:  X, col:  X):	Global variable must start with g_
```

**Additional infos**
 - OS: macOS Mojave Version 10.14.6 (18G9216)
 - python --version: 2.7.16
 - norminette -v: 3.2.95

**Additional context**
[Topic](https://stackoverflow.com/a/10321474/14477874) about the portability of the `char *envp` variable (third argument in `main`).

**Comment by N0ich** [comment]
Hello,
I'm adding a special case for environ to be declared in the global scope. Do you have any other that come to mind?

**Comment by leeoocca** [comment]
Hi Vincent,
That should be all for now. Nothing else came to mind.
Thanks :)
