### ISSUE TITLE
tests/rules/ok_comment.c does not contain any comments

### ISSUE THREAD

**Issue by bh90210** [42School/norminette#163]
It is not a bug per se but going through tests to see the implementation of `comments` rules of norm v3 looking in the ok_comment.c I found no comments. 

https://github.com/42School/norminette/blob/master/norminette/tests/rules/ok_comment.c

ps. going through other tests I found OK `.c` files with comments 
ie https://github.com/42School/norminette/blob/a16b54923b3c459371342354eafc727a5eb70614/norminette/tests/rules/ok_func_classic.c
https://github.com/42School/norminette/blob/a16b54923b3c459371342354eafc727a5eb70614/norminette/tests/rules/ok_func_ptr.c
so I did found out what I was looking for but thought of letting u know :)
unless the ok_comment.c was actually never meant for comments and I just misunderstood in which case I'm preemptively  sorry for opening the ticket!

**Comment by N0ich** [comment]
Nice catch. I will probably change it at some point but for now the testing suite is pretty fine as is. 
Have a great day!
