### ISSUE TITLE
Norminette infinite loop with this student code.

### ISSUE THREAD

**Issue by greatvengeance** [42School/norminette#168]
**Describe the bug**
When the workers(student iMacs) accepts this code for review infinite loops occurs and high cpu load appears.

**Erroneous code**
Check pinned files

**Additional infos**
 - OS: ProductName:	Mac OS X
           ProductVersion:	10.14.6
           BuildVersion:	18G9216
 - python --version:  Python 2.7.16
 - norminette -v: 3.3.0

**Additional context**

**Comment by greatvengeance** [comment]
[ft_print_comb.txt](https://github.com/42School/norminette/files/6741816/ft_print_comb.txt)

**Comment by N0ich** [comment]
Hello,

I apologize but that's beyond the scope of the norminette and would require quite a lot of work to fix.
Norminette is expected to work on files that compile. Using it on files that don't compile may containt unexpected behaviour, and that's a design choice.

Also, you are using python2.7 and norminette isn't developped for 2.7. Please use a more up to date version (3.7, 3.8, 3.9..)
