### ISSUE TITLE
Space after Break and Continue

### ISSUE THREAD

**Issue by psudo-dev** [42School/norminette#171]
https://github.com/42School/norminette/blob/a16b54923b3c459371342354eafc727a5eb70614/norminette/rules/check_expression_statement.py#L52-L53

```c
if (i > 0)
    break ;
```

Is there a reason why **`break`** and **`continue`** need a *`space`* after it? 

I can understand why **`return`** demands a space since you always have to return something, even if it's a **(0)**. But on **`break`** and **`continue`** it's just odd to have a *`space`* and then a *semicolon*.

I tried to find an explanation but I couldn't find it. Couldn't **`break`** and **`continue`** be an exception?

**Comment by N0ich** [comment]
Hello,

The only reason is the one you mentionned, they are simply not an exception and fall under the "keyword" category. 
I'll take it up to see if we want to change it.

Thanks for the ticket
