### ISSUE TITLE
operator bugs

### ISSUE THREAD

**Issue by nori26** [42School/norminette#173]
```
int	main(void)
{
	int	i;
	int	*j;
	int	k;

	k = 0;
	j = &k;
	i = -!j;
	i = -!*j;
	i = -!!j;
	i = ~*j;
	i = ~!j;
	i = ~!j;
	i = -~k;
	i = !-k;
	i = !+k;
	i = !~k;
	i = ~!~k;
	i = ~~~~~~~~k;
}
```
Error: SPC_AFTER_OPERATOR   (line:  11, col:   9):      missing space after operator
Error: SPC_AFTER_OPERATOR   (line:  12, col:   9):      missing space after operator
Error: SPC_AFTER_OPERATOR   (line:  13, col:   9):      missing space after operator
and more message...

combinations of "-+~*" will cause bugs.

**Comment by snara-42** [comment]
`else if (0 < i && -1 != len)`
Error: SPC_AFTER_OPERATOR 

norminette -v
norminette 3.3.1
python -V
Python 3.9.5

**Comment by snara-42** [comment]
> ```
> int	main(void)
> {
> 	int	i;
> 	int	*j;
> 	int	k;
> 
> 	k = 0;
> 	j = &k;
> 	i = -!j;
> 	i = -!*j;
> 	i = -!!j;
> 	i = ~*j;
> 	i = ~!j;
> 	i = ~!j;
> 	i = -~k;
> 	i = !-k;
> 	i = !+k;
> 	i = !~k;
> 	i = ~!~k;
> 	i = ~~~~~~~~k;
> }
> ```
full list of output: 

Error: SPC_AFTER_OPERATOR   (line:   9, col:   9):missing space after operator
Error: SPC_AFTER_OPERATOR   (line:  10, col:   9):missing space after operator
Error: SPC_AFTER_OPERATOR   (line:  11, col:   9):missing space after operator
Error: SPC_AFTER_OPERATOR   (line:  12, col:   9):missing space after operator
Error: SPC_AFTER_OPERATOR   (line:  13, col:   9):missing space after operator
Error: SPC_AFTER_OPERATOR   (line:  14, col:   9):missing space after operator
Error: SPC_AFTER_OPERATOR   (line:  15, col:   9):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  15, col:   9):missing space before operator
Error: SPC_AFTER_OPERATOR   (line:  16, col:  10):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  16, col:  10):missing space before operator
Error: SPC_AFTER_OPERATOR   (line:  17, col:  10):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  17, col:  10):missing space before operator
Error: SPC_AFTER_OPERATOR   (line:  18, col:  10):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  18, col:  10):missing space before operator
Error: SPC_AFTER_OPERATOR   (line:  19, col:   9):missing space after operator
Error: SPC_AFTER_OPERATOR   (line:  19, col:  11):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  19, col:  11):missing space before operator
Error: SPC_AFTER_OPERATOR   (line:  20, col:   9):missing space after operator
Error: SPC_AFTER_OPERATOR   (line:  20, col:  10):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  20, col:  10):missing space before operator
Error: SPC_AFTER_OPERATOR   (line:  20, col:  11):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  20, col:  11):missing space before operator
Error: SPC_AFTER_OPERATOR   (line:  20, col:  12):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  20, col:  12):missing space before operator
Error: SPC_AFTER_OPERATOR   (line:  20, col:  13):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  20, col:  13):missing space before operator
Error: SPC_AFTER_OPERATOR   (line:  20, col:  14):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  20, col:  14):missing space before operator
Error: SPC_AFTER_OPERATOR   (line:  20, col:  15):missing space after operator
Error: SPC_BFR_OPERATOR     (line:  20, col:  15):missing space before operator
Error: SPC_BFR_OPERATOR     (line:  20, col:  15):missing space before operator
