### ISSUE TITLE
Uncaught exception with invalid utf-8 file

### ISSUE THREAD

**Issue by Neirpyc** [42School/norminette#177]
**Describe the bug**
Uncaught exception when invalid utf-8 character is encountered in file.

**Erroneous code**
I have no idea

**Additional infos**
 - OS: 5.4.92-gentoo-x86_64
 - python --version: Python 3.9.5
 - norminette -v: norminette 3.3.0

**Additional context**
```sh
> hexdump -C file.c 
00000000  94                                                |.|
00000001
> norminette file.c
Traceback (most recent call last):
  File "~/.local/bin/norminette", line 33, in <module>
    sys.exit(load_entry_point('norminette==3.3.0', 'console_scripts', 'norminette')())
  File "~/.local/lib/python3.8/site-packages/norminette/__main__.py", line 96, in main
    source = f.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 0: invalid start byte
```

**Comment by N0ich** [comment]
Hello,

I'm having a hard time reproducing the crash, most of them are handled by the parser and i can't seem to make this one crash.
Can you send me the file itself?
Thanks

**Comment by Neirpyc** [comment]
Here is the [file.zip](https://github.com/42School/norminette/files/6850434/file.zip) (Github won't let me upload a `.c`, of course you have to unzip it).

**Comment by N0ich** [comment]
Thank you - I can't actually parse & use the value, but ive made a clearer error message rather than a crash :) 
Will be up with next update.
