### ISSUE TITLE
Infinite loop with a single opening parenthesis '('

### ISSUE THREAD

**Issue by Neirpyc** [42School/norminette#179]
**Describe the bug**
When a file contains only a parenthesis, the norminette hangs for ever instead of detecting a parenthesis miss match.

**Erroneous code**
I have no idea

**Additional infos**
 - OS: 5.4.92-gentoo-x86_64
 - python --version: Python 3.9.5
 - norminette -v: norminette 3.3.0

**Additional context**
```sh
> hexdump -C file.c
00000000  28 0a                                             |(.|
00000002
> norminette file.c
```

**Comment by N0ich** [comment]
Fixed with the previous issue. Will be pushed by today
