### ISSUE TITLE
Norminette recognizes a function as a global variable

### ISSUE THREAD

**Issue by dimonbavly** [42School/norminette#182]
**Describe the bug**
Subject Prototype:

**Erroneous code**
`static	char*(*sprep(char j)) (char *s, t_td *data);`

**Additional infos**
 - OS: Xubuntu 20.04
 - python --version: 3.8.10
 - norminette -v: 3.3.1

**Additional context**
How to fix it?

**Comment by N0ich** [comment]
Hello,
The proper way to define such a function prototype is :
`static char *(*sprep(char j))(char *s, t_td *data);`

Have a good day
