### ISSUE TITLE
Incorrect VLA_Forbidden in enum.

### ISSUE THREAD

**Issue by ywake** [42School/norminette#185]
**Describe the bug**
`Variable length array forbidden` is occur when specifying the array length using the enum value.

**Erroneous code**
```c
enum e_example
{
    aaa,
    bbb,
    ccc,
    enum_len
};

int main(void)
{
    int array[enum_len]; // Error: VLA_FORBIDDEN
}
```

**Comment by vinicius507** [comment]
It also happens with `const int` values.

![image](https://user-images.githubusercontent.com/6608056/126730095-7042cb5f-e04c-4523-b3a2-d6a1a390b439.png)

**Comment by N0ich** [comment]
Alright so,

The goal of VLA forbidden is to prevent changing the variable length on the fly.
The code does not always have the information of what kind of variable this is (for instance here, these could be defined in a header and not available here.)
The best way to have a constant is to use capital letters only, as the norminette considers capital letter to be a constant and will let you defin an array this way.

have a good day!

**Comment by ywake** [comment]
Wow! It was a lack of my understanding of norminette.
Thank you for your response!
