### ISSUE TITLE
Norminette false positive TOO_MANY_TAB

### ISSUE THREAD

**Issue by louchebem06** [42School/norminette#189]
**Describe the bug**
The norminette tells me that my code is not at the norm.

**Erroneous code**
```c
while (tmp[++i])
	if (isredirection(tmp[i]) == 0)
		add_value(&redict[j]->value, tmp[i]);
	else
	{
		j++
		redict[j] = ft_calloc(sizeof(t_redirection), 1);
		redict[j]->type = isredirection(tmp[i]);
	}
```
```norminette
TOO_MANY_TAB 71 - 76
```

**Additional infos**
 - OS: ```Linux PC-Gamer 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux```
 - python --version: ```Python 3.7.3```
 - norminette -v: ```norminette 3.3.1```

**Additional context**
![Capturer](https://user-images.githubusercontent.com/34492446/126066635-9d802507-7890-496f-baa9-69a9f8d651d9.PNG)
![Capturerw](https://user-images.githubusercontent.com/34492446/126066638-7eb7f938-8d11-48ac-90ad-d635f0a906b2.PNG)
![Capturerwasdas](https://user-images.githubusercontent.com/34492446/126066640-ce03824f-06e2-43d4-afa9-ded9efd09a96.PNG)
![Capturerasdasd](https://user-images.githubusercontent.com/34492446/126066642-fa8f0fa1-fc69-42ad-a1bb-51c134e04005.PNG)

**Comment by Nazza01** [comment]
Hi, in the while loop you will need to include curly braces as the lines below it are more than 2 lines.
Fix:
`while (tmp[++i])\t`
`{`
`    if (isredirection(tmp[i]) == 0)`
        `add_value(&redict[j]->value, tmp[i]);`
`}`

**Comment by louchebem06** [comment]
> Hi, in the while loop you will need to include curly braces as the lines below it are more than 2 lines.
> Fix:
> `while (tmp[++i])\t`
> `{`
> ` if (isredirection(tmp[i]) == 0)`
> `add_value(&redict[j]->value, tmp[i]);`
> `}`
The braces must be inserted in the case where there is more than one instruction, except in my case there is only one instruction because an else can only be after an if, so my if else and an instruction.

**Comment by N0ich** [comment]
Hello,
For now, multi-line conditions must be bracketed (as expected by C language) and control structure that include multi-line control structures must be bracketed as well, which is why the second code is valid while the first isn't.

Thank you for you report.
