### ISSUE TITLE
indent bug

### ISSUE THREAD

**Issue by nori26** [42School/norminette#190]
```
int	main(void)
{
	while (1)
		if (0)
			;
	else
		(void)0;
}
```
$ norminette main.c
main.c: OK!

```
int	main(void)
{
	while (1)
		if (0)
			;
		else
			(void)0;
}
```
$ norminette main.c
main.c: Error!
Error: TOO_MANY_TAB         (line:  18, col:   1):      Extra tabs for indent level
Error: TOO_MANY_TAB         (line:  19, col:   1):      Extra tabs for indent level

```
int	main(void)
{
	while (1)
		if (0)
			;
	else
		;
}
```
$ norminette main.c
main.c: Error!
Error: EMPTY_LINE_FUNCTION  (line:  19, col:  10):      Empty line in function

**Comment by N0ich** [comment]
Hello,
For now, multi-line conditions must be bracketed (as expected by C language) and control structure that include multi-line control structures must be bracketed as well, which is why the second code is valid while the first isn't.

Thank you for you report.
