### ISSUE TITLE
Recursive error

### ISSUE THREAD

**Issue by MardanovTimur** [42School/norminette#196]
Im from Kazan 21school campus - Bocal

We noticed - if the file was not completed to the end (not valid) - norminettev3 goes to recursive loop (cant exit)

All our iMacs was heated up to 90C. Fix this please

```
void   ft_putstr_non_printable(char *str)
{
       write (*str)
       {
               if (*str < 26 || *str
``` 

try to launch this

**Comment by N0ich** [comment]
Hello, and thank you for your issue.
This has already been fixed but the release isn't yet ready. Should be good soon.
Sorry for the inconvenience!

**Comment by MardanovTimur** [comment]
Please, do not close the issue while it is not fixed
