### ISSUE TITLE
Erroneous tab space calculation with static function prototypes

### ISSUE THREAD

**Issue by docgloucester** [42School/norminette#198]
**Describe the bug**
When tab-aligning two function prototypes, one static and the other not, the space used by the `static` keyword seems to be ignored.

**Erroneous code**

Take this example code.

```C
static double	calculate(double nb, double approx, double prev_approx)
{
	if (approx == prev_approx)
		return (approx);
	return (calculate(nb, (approx + nb / approx) / 2, approx));
}

double			ft_sqrt(double nb)
{
	if (!nb)
		return (0);
	return (calculate(nb, 50, 0));
}
```
In order to visually align the two functions prototypes in  a properly configured editor (ie. not in github visualisation 🙃), there has to be one tab between `static double` and `calculate`, and three tabs between `double` and `ft_sqrt`, as shown here.
![](https://i.imgur.com/z2jh2IE.png)

However, the norminette raises the following error about the second prototype :
`Error: TOO_MANY_TABS_FUNC   (line:   8, col:  13):      extra tabs before function name`

The error persists until there's only one tab left in the declaration of the second function, which leaves the result unaligned.
This result would however work if the keyword `static` wasn't present in the first prototype.

This behaviour has corresponded to all my tests around this issue, so I'm pretty confident that's it.

**Additional infos**
 - OS: MacOS Mojave
 - python --version: Python 3.7.4
 - norminette -v: norminette 3.3.2

**Comment by docgloucester** [comment]
I have noticed the same behaviour for the `const` keyword.

**Comment by N0ich** [comment]
Hello,

Functions no longer need to be tab aligned. you simply need to put a single tab after a func proto/decl
