### ISSUE TITLE
More general issue with tab space calculation for functions alignment

### ISSUE THREAD

**Issue by docgloucester** [42School/norminette#199]
**Describe the bug**
There seems to be a more widespread issue with alignment detection in the norminette than the one I thought I had identified at #198 

**Erroneous code**
```C
int		inject_line(char *str, char **line)
{
	return ((int)str);
}

char	*rest_of_buffer(char *str)
{
	return (str);
}
```

With a proper 4-spaces-per-tab editor, both functions are aligned with 1 tab for char* et 2 tabs for int, as seen here
![](https://i.imgur.com/ebOiVyU.png)

However the norminette still spits out :
`Error: TOO_MANY_TABS_FUNC   (line:   1, col:   5):      extra tabs before function name`

**Additional infos**
 - OS: MacOS Mojave
 - python --version: Python 3.7.4
 - norminette -v: norminette 3.3.2

**Comment by N0ich** [comment]
Closing this one as well, thanks for the issues but its more related to the rule change that was chosen
