### ISSUE TITLE
Newline in function declaration

### ISSUE THREAD

**Issue by lsoulier42** [42School/norminette#20]
The new version of norminette founds an error when putting a newline in function declaration which is not mention on normv3 pdf

**Comment by Neirpyc** [comment]
I think you should add a minimal reproducible example :)

But I've had the same bug, and obviously, limiting lines to 80characters and not allowing splitting a line is stupid, that's obviously _Norminette_'s fault!

**Comment by N0ich** [comment]
Please send us an example indeed :)

**Comment by lsoulier42** [comment]
int             execute_child_process(t_data *msh_data, t_cmd *cmd, int previous_fd, int pipefd[2]); => LINE TOO LONG
int             execute_child_process(t_data *msh_data, 
    t_cmd *cmd, int previous_fd, int pipefd[2]); => NEWLINE FOUND IN DECLARATION

**Comment by N0ich** [comment]
I'll see whether we need to update the pdf as it is intended behavior, or if we want to modify the code to allow it.

**Comment by lsoulier42** [comment]
Please don't modify the pdf, how are we supposed to put understandable variables names if we can't split the line for the declaration of functions ? Almost every function with a pointer of function and more than one parameter exceed 80 char... And some prototypes of functions given in piscine won't fit the norm if you can't split this line...

**Comment by N0ich** [comment]
Removed in upcoming update
