### ISSUE TITLE
Problem with tabulation in a typedef'd struct declaration

### ISSUE THREAD

**Issue by docgloucester** [42School/norminette#200]
**Describe the bug**
In a struct, the norm expects you to tab-align the name of the struct.
But in a typedef'd struct, the norminette raises the TAB_REPLACE_SPACE error when a tab is employed.

**Erroneous code**
The following code :
```C
typedef struct	s_list
{
	void			*content;
	struct s_list	*next;
}				t_list;
```
raises the aforementioned error.
The same code but with a space instead of a tab in the declaration passes the norminette while being erroneous.

While the same code without the typedef doesn't :
```C
struct			s_list
{
	void			*content;
	struct s_list	*next;
};
```
**Additional infos**
 - OS: MacOS Mojave
 - python --version: Python 3.7.4
 - norminette -v: Norminette 3.3.2

**Comment by fifididi** [comment]
I will add to this that the below code also triggers an inconsistency:

```c
typedef struct s_flag_mod {
	char	flag;
	void	(*f)(t_flag *flags);
}			t_flag_mod;
```

The above code triggers two erroneous errors: TAB_REPLACE_SPACE and SPACE_REPLACE_TAB for the function pointer member when it is aligned and written out in accordance with the norm. 

I have noticed that for structs that contain a similar structure but more than one argument in the function pointer, that there is no such errors.  

The code below doesn't trigger any errors:

```c
typedef struct s_fmt {
	char	type;
	void	(*f)(t_flag *flags, t_buf *buf, va_list va);
}			t_fmt;
```

**Comment by N0ich** [comment]
Hello,

When writing the typedef name (here t_list) you don't need to tab align your struct name since its part of its "type" 
If you dont specify the typedef name the struct needs to be tabbed.
Ill see whether we want to fix the second part for consistency.

Regarding the second issue by @fifididi, im on it.
