### ISSUE TITLE
clang attributes

### ISSUE THREAD

**Issue by vneelix** [42School/norminette#203]
**Describe the bug**
The presence of attributes of functions breaks the norm

**Erroneous code**
```
float __attribute__((overloadable)) len(t_float2 a)
{
	t_float2	v;

	v = a;
	return (sqrt(a.x * a.x + a.y * a.y));
}
```

**Additional infos**
 - OS: macos 10.14.6
 - python --version: Python 3.7.8
 - norminette -v: norminette 3.3.2

**Additional context**
The attribute argument does not matter

**Comment by vneelix** [comment]
There is also a problem with attributes of functions in the header files

**Comment by N0ich** [comment]
Hello, 
Can you give me an example for the second problem?
