### ISSUE TITLE
MISSING_IDENTIFIER triggers for valid types.

### ISSUE THREAD

**Issue by fifididi** [42School/norminette#210]
**Describe the bug**
The `MISSING_IDENTIFIER` triggers for valid types, in my case `long long`

**Erroneous code**
Any function with a prototype such as this one `void test(long long n)`

**Additional infos**
 - norminette -v: 3.3.31

**Comment by N0ich** [comment]
Hello,
`long long` is an alias to `long long int` and long in the norm is only considered as a misc. specifier (like `const`, `unsigned`...) so it's required to add the `int` for the type.

**Comment by fifididi** [comment]
OK great...
the following code still triggers the error...

```c
int	test(long long int n)
{
	return (5);
}
```

**Comment by fifididi** [comment]
I can't reopen the issue @N0ich

**Comment by vinicius507** [comment]
The same is happening to me.

![image](https://user-images.githubusercontent.com/6608056/131376724-952f1f0d-1b80-4a97-89b2-74c4a07df3cf.png)

**Comment by N0ich** [comment]
thank you, i'll look into it

**Comment by N0ich** [comment]
Alright i'm releasing a hotfix (`long long` is a valid identifier)

**Comment by JustLinuxUser** [comment]
norminette 3.3.55 MISSING_IDENTIFIER warning when a function parameter is passed in:
```c
void	ft_foreach(int *tab, int length, void(*f)(int))
{
	int	i;

	i = 0;
	while (i < length)
	{
		f(tab[i]);
		i++;
	}
}
```
ft_foreach is ex00 from C11, and it doesn't pass the latest norminette

**Comment by JustLinuxUser** [comment]
Looking at the [grammar](https://learn.microsoft.com/en-us/cpp/c-language/summary-of-declarations?view=msvc-170) I would recommend not bothering with a full type declaration parser implementation or a partial that covers "almost all" cases, but instead add a flag to disable that type of checking

**Comment by JustLinuxUser** [comment]
Ok, so looking at the NORM, there is nothing prohibithing putting a space in between the function return type and the rest of it's signature, like so: `void (*f)(int)`, even though in the task pdf they are together. So I guess not such a big deal after all :)
