### ISSUE TITLE
Line break in function parameters are triggering TAB_INSTEAD_SPC

### ISSUE THREAD

**Issue by vinicius507** [42School/norminette#211]
**Describe the bug**
When surpassing the line limit, breaking the line in the function parameters is now triggering `TAB_INSTEAD_SPC`.

![image](https://user-images.githubusercontent.com/6608056/131564975-697eae60-a377-45d2-8cdb-d6d18eb24c78.png)

**Erroneous code**
```c
static inline void	*wordchr(const unsigned long int *word, unsigned long int
	mask, size_t *n)
{
	unsigned long int	hi;
	unsigned long int	lo;
	unsigned long int	longword;
	const unsigned char	*ptr;
        // [...]
}
```

**Additional infos**
 - OS: `Linux myriad 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux`
 - python --version: 3.9.6
 - norminette -v:  3.3.32

**Additional context**
It started happening at Norminette 3.3.31

**Comment by louchebem06** [comment]
For the standard to be valid, your line would have to end with a comma
```c
static inline void	*wordchr(const unsigned long int *word,
	unsigned long int mask, size_t *n)
{
	unsigned long int	hi;
	unsigned long int	lo;
	unsigned long int	longword;
	const unsigned char	*ptr;
}
```

**Comment by vinicius507** [comment]
Great! Thanks for the heads-up @louchebem06 ;)

Closing.
