### ISSUE TITLE
Norminette fails when their is a space at the bank line after the code

### ISSUE THREAD

**Issue by TamLem** [42School/norminette#212]
**Describe the bug**
Norminette fails when their is a space at the bank line after the code.
Error message ==  "Error: Code ended unexpectedly."

**Erroneous code**
``` 
/* tab or space at end line after the last function in the file fails the code */

int	main(void)
{
	return (0);
}
--> //tabs or spaces here
```
**Additional infos**
 - OS: Mac
 - python 2.7:
 - norminette 3:

**Additional context**

**Comment by N0ich** [comment]
Hello,
Can you provide an example?

**Comment by TamLem** [comment]
By norm rules, we have to add a blank line after each function, if there are any spaces or tabs on that line, it would fail producing  "Error: Code ended unexpectedly."

**Comment by fifididi** [comment]
This is normal behaviour, read the norm more carefully. `A line can never end with spaces or tabulations.`
Also when people ask you for an example erroneous code, they expect code, not an error message.

**Comment by TamLem** [comment]
@fifididi A normal behavior of norminette is to produce an error, not fail. The case it quite clear and need no example for one who understands human language too.

**Comment by N0ich** [comment]
If you can't provide example, there is no bug. You managed to poorly ask your question and i can't decipher what's not working.
Have a great day.

**Comment by TamLem** [comment]
Yea, I get it, you have a lot to fix.
