### ISSUE TITLE
Is norminette only accessible from 42 computers? 

### ISSUE THREAD

**Issue by ErmandH** [42School/norminette#215]
Cant I use it from my own computer from home

**Comment by louchebem06** [comment]
yes
https://github.com/42School/norminette/blob/master/README.md
```shell
python3 -m pip install --upgrade pip setuptools
python3 -m pip install norminette
```

**Comment by ErmandH** [comment]
> yes
> https://github.com/42School/norminette/blob/master/README.md
> 
> ```shell
> python3 -m pip install --upgrade pip setuptools
> python3 -m pip install norminette
> ```

but it says couldnt establish the TCP Connection
