### ISSUE TITLE
False positive when using operator * after a variable surrounded by parenthesis 

### ISSUE THREAD

**Issue by tcarasso** [42School/norminette#218]
**Describe the bug**
When trying to multiply a casted in int float stored inside a structure, norminette will interpret the "\*" operator as a pointer and therefore report en error if you put a space after it. My guess is that it would interpret any variable surrounded by parenthesis as followed by a "\*" as a pointer, but not sure and I didn't test it more.

**Erroneous code**
Error: SPC_AFTER_POINTER

**Additional infos**
 - OS: Linux (ubuntu from VM)
 - python --version: 2.7.17
 - norminette -v: 3.3.2

**Additional context**
code example:  ((int)(env->p->f_y) * 64)

**Comment by N0ich** [comment]
Hello, please update your norminette version. Latest is 3.3.32, and this looks fixed as I can't seem to reproduce it.test

**Comment by tcarasso** [comment]
Still having the bug in 3.3.32, here is the part of my code producing it : 
`
void	draw_player(t_env *env)
{
	env->p->f_x += (env->p->x - env->p->f_x) * 0.5;
	env->p->f_y += (env->p->y - env->p->f_y) * 0.5;
	draw_on_image(env->main_img, env->p->img, ((int)(env->p->f_y) * 64),
		((int)(env->p->f_x) * 64));
}
`

**Comment by N0ich** [comment]
I'll check it out, thank you
