### ISSUE TITLE
Can no longer use anonymous / embedded structs

### ISSUE THREAD

**Issue by abrabant-42** [42School/norminette#22]
```c
#ifndef HEADER_H
# define HEADER_H

typedef struct s_mystruct
{
	int	x;
	int	y;
	struct s_embeded
	{
		int	height;
		int	width;
	}	anonymous;
}	t_mystruct;

#endif
```

As seen in the code snippet above, using anonymous or embedded structures seems to be bugged. 

I tried several alignment styles, to name the struct or not,  but it seems that the only solution to that issue is to `typedef` the structure which is to be embedded. This is annoying as there's no need for a `typedef` in that case. 

The PDF doesn't say a thing about that, and it was possible to do that back at the norm v2.

**Comment by N0ich** [comment]
Can you use the embedded code instead of a screenshot?

**Comment by abrabant-42** [comment]
Done.  Moreover, as I said I tried several alignment styles to conform to the norm (we must put one space after a struct keyword, but at the same time we need to align the struct members, so I don't really know how we are supposed to do that).
