### ISSUE TITLE
Defining pointer bug

### ISSUE THREAD

**Issue by ErmandH** [42School/norminette#220]
`
 17         int     i;
 18         char    *ptr;
` 
 When im defining char pointer it always says 
 
Error: MISALIGNED_VAR_DECL  (line:  18, col:  13):      Misaligned variable declaration

It says that even on github piscine files
**Additional infos**
 - OS: Windows
 - python --version: Python 3.9.6
 - norminette -v:  norminette 3.3.32

**Comment by N0ich** [comment]
Hello, it seems you are doing something wrong regarding the norm. It doesn't look like this is a bug.

**Comment by samurusov** [comment]
Same here. Have you found the solution to that? I checked my code many times and not sure what's wrong. 
![image](https://user-images.githubusercontent.com/14890643/164993367-330e7f6e-356c-4164-a92f-6330ec7ce595.png)

**Comment by ErmandH** [comment]
It s probably because of Linux when I was at 42 school this problem didnt occure so ignore it

**Comment by axlstephano** [comment]
I had the same problem, and I realized that it was because the variable declaration must always be aligned, the beginning of the variable name must start at the same point.

**Comment by FaelXavo** [comment]
For all of you guys facing the same problem, **norminette** seems to have some problems with the alignment of your program when you declare a "**integer**". Don't ask me why.
### In any case,  _just use tab once more **ONLY on the int declaration line**_. I hope it helps you guys and good look in the Piscine!!!

**Comment by mufazzalshokh** [comment]
When I got this problem, 1/2 extra tab helps. Because, in VIM it does not shows the syntax but ex in VS code it shows. Enjoy guys and good luck with your Piscine!)

**Comment by izzytoot** [comment]
Open vim in the terminal and type:
esc
:set tabstop=4

Then align your variables in vim (terminal).

**Comment by MohamedKadi** [comment]
THANKS LOL I SUFFERED TO SOLVE THIS PROBLEM, JUST USED 2 TABS THANKS FaelXavo

**Comment by R3N4N-147** [comment]
I was having the same problem. Here's the solution:


char buffer[3]; // only one tab
int n; // only one tab

Then, I had a brilliant idea: add an extra tab between *int* and *n*. And... it worked! It was just the comma that was misaligned.

**Comment by justshobee** [comment]
I had this problem before
char *s1;//one tab
int len;// two tab
and I fixed it by using two tabs after the int type instead of one
