### ISSUE TITLE
norminette command not found

### ISSUE THREAD

**Issue by 48d31kh413k** [42School/norminette#224]
**Erroneous code**
hp@DESKTOP-C826HA4 /cygdrive/d/Téléchargements/norminette
$ python3 -m pip install --upgrade pip setuptools
python3 -m pip install norminette
Requirement already satisfied: pip in c:\users\hp\appdata\local\packages\pythons
oftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\si
te-packages (21.2.4)
Requirement already satisfied: setuptools in c:\users\hp\appdata\local\packages\
pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\pyth
on39\site-packages (58.0.4)
Requirement already satisfied: norminette in c:\users\hp\appdata\local\packages\
pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\pyth
on39\site-packages (3.3.32)

hp@DESKTOP-C826HA4 /cygdrive/d/Téléchargements/norminette
$ python3 -m pip install --upgrade norminette
Requirement already satisfied: norminette in c:\users\hp\appdata\local\packages\
pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\pyth
on39\site-packages (3.3.32)

hp@DESKTOP-C826HA4 /cygdrive/d/Téléchargements/norminette
$ pip3 install -r requirements.txt
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: argparse
Successfully installed argparse-1.4.0

hp@DESKTOP-C826HA4 /cygdrive/d/Téléchargements/norminette
$ cygstart --action=runas python3 setup.py install

hp@DESKTOP-C826HA4 /cygdrive/d/Téléchargements/norminette
$ norminette
-bash: norminette: command not found

**Additional infos**
 - OS: Windows10
 - python --version: 3.9.7
 - norminette -v: 3.3.32
![image_2021-09-16_143645](https://user-images.githubusercontent.com/65833007/133622051-ebc311c7-2c8c-42fc-b561-72e7e1b6ae7d.png)

**Comment by vinicius507** [comment]
Pip installs the package as a user package. Meaning it is in `~/.local/bin/norminette`. You need to add `~/.local/bin` to your PATH.

To do so just add the following line to your `.bashrc`/`.zshrc`:

```sh
export PATH="$HOME/.local/bin:$PATH"
```

Then close and open your terminal.

**Comment by 48d31kh413k** [comment]
Thank you for answering.
I use cygwin and git bash on Windows10.
I've done all the steps but the problem is not solved yet.

**Comment by vinicius507** [comment]
> Thank you for answering.
> I use cygwin and git bash on Windows10.
> I've done all the steps but the problem is not solved yet.

Ok, I never used `git bash` with Windows 10. You might be able to run norminette if you try to use it as a python module, e.g. `python -m norminette FILE`

**Comment by 48d31kh413k** [comment]
The problem is solved, thank you so much for your help and time.

**Comment by vinicius507** [comment]
> The problem is solved, thank you so much for your help and time.

You're welcome :)
