### ISSUE TITLE
Allow comments after #endif statements

### ISSUE THREAD

**Issue by pde-bakk** [42School/norminette#227]
Norminette doesn't allow simple comments after preproccesor staments anymore.

**Erroneous code**
```c
#ifdef SOMETHING
#endif //OPCODE_H
```

**Additional infos**
 - OS: Ubuntu 20.04
 - python --version: 3.8.10
 - norminette -v: 3.3.32

**Additional context**
Adding simple comments after `#endif` statements improve readability a lot, because you can easily see to which `#ifdef` statement it belongs.
CLion also does this by default when you create a .h file.

**Comment by pde-bakk** [comment]
:cry:

**Comment by N0ich** [comment]
hello, your issue has been fixed (as you can see in the commit) ill do the release shortly
