### ISSUE TITLE
Const variables can't be capitalized

### ISSUE THREAD

**Issue by pde-bakk** [42School/norminette#228]
**Describe the bug**
Norminette doesn't allow the use of capitals anymore in variables.

**Erroneous code**
```c
const int OP_COUNT = arg / 2;
```

**Additional infos**
 - OS: Ubuntu 20.04
 - python --version: 3.8.10
 - norminette -v: 3.3.32

**Additional context**
Most languages use CAPITALIZED_SNAKE_CASE for const variables, so why can't we?

**Comment by N0ich** [comment]
Hello,
While I agree with the reasoning, capitalized identifier are used for define only.
const variable should be named with lower letters.

**Comment by pde-bakk** [comment]
:cry:
