### ISSUE TITLE
cannot define NULL

### ISSUE THREAD

**Issue by antikostya** [42School/norminette#229]
**Describe the bug**
if I want to define NULL I get INCORRECT_DEFINE for any value in define

**Erroneous code**
```c
#define NULL 0
```
norminette returns:
```
Error: INCORRECT_DEFINE     (line:   1, col:   7):	Incorrect values in define
```
#
**Additional infos**
 - OS: `Linuxmint 20.2 uma`
 - python --version: `Python 3.8.10`
 - norminette -v: `norminette 3.3.32`

**Comment by N0ich** [comment]
Hello,
For now, NULL is not considered a valid identifier, as in most cases, it's already defined by various includes. Only non-existing identifier can be defined with the norminette
