### ISSUE TITLE
Maybe a bug with "too many tabs"

### ISSUE THREAD

**Issue by gasselin42** [42School/norminette#234]
Unsure if this is a bug or not but I had this code below and norminette triggered me "too many tabs" errors on line 72 & 74, when I have clearly 2 tabs from the if. The norm errors disappear when I remove the set of parenthesis just before both get_time calls.

<img width="515" alt="Screen Shot 2021-09-27 at 11 21 54 AM" src="https://user-images.githubusercontent.com/80594358/134939299-297194eb-edcb-41fb-8547-b89b1e9b9722.png">

**Comment by vinicius507** [comment]
Can you paste a section of the code so I can reproduce it here?

**Comment by clbrunet** [comment]
This code produce a TOO_MANY_TAB error :
```c

foobar(123456789, 123456789, 123456789,
		123456789);
```
While this does not :
```c
test = foobar(123456789, 123456789, 123456789,
		123456789);
```
There are 2 tabs for the second lines of both examples.

**Comment by vinicius507** [comment]
If I'm not mistaken the number of tabs on the second line of a function call is relative to the indentation on the first line. In the first example, the function call is at the start of the line, whereas in the second example it is in a instantiation. So, on the first example, the second line should have a single tab preceding it.
