### ISSUE TITLE
Problem with function definitions that start with parentheses

### ISSUE THREAD

**Issue by SaumonDesMers** [42School/norminette#235]
This function is problematic (this one returns a pipe table).

![Screenshot from 2021-09-28 17-32-00](https://user-images.githubusercontent.com/61418642/135126842-f5fd4e5b-e1b1-464d-baad-68a3067752d7.png)
![Screenshot from 2021-09-28 17-17-48](https://user-images.githubusercontent.com/61418642/135127010-46cf2821-3a95-4e4b-853c-03c9349fd833.png)

But this one is good except that I have to put a tab on line 19 between const and int for no reason (this one returns a pointer to function).

![Screenshot from 2021-09-28 18-28-09](https://user-images.githubusercontent.com/61418642/135128606-2669ecff-dc33-49a1-a945-ba7b3f133f60.png)

Also in the .h, the norminette doesn't seem to understand what's going on.

![Screenshot from 2021-09-28 18-36-05](https://user-images.githubusercontent.com/61418642/135129010-d68493d2-3918-4239-96f3-b435a142b360.png)
![Screenshot from 2021-09-28 18-36-17](https://user-images.githubusercontent.com/61418642/135129021-00319bab-b0c1-4311-a231-922b49d659b2.png)

 - OS: Ubuntu
 - python --version: Python 2.7.18
 - norminette -v: norminette 3.3.1

**Comment by N0ich** [comment]
Hello,

Can you provide code instead of the screenshots ? There's a lot to type here :)

**Comment by SaumonDesMers** [comment]
int (*open_pipe(int nb_of_cmd))[2]
{
int i;
t_pipe pipe_fd;

pipe_fd = malloc(sizeof(int [2]) * (nb_of_cmd - 1));
if (error_catch(pipe_fd == 0, "system", "fail to malloc pipe table"))
return (NULL);
i = 0;
while (i < nb_of_cmd - 1)
{
if (error_catch(pipe(pipe_fd[i++]) == -1, "system",
"fail to open pipe"))
{
while (--i)
{
close(pipe_fd[i][0]);
close(pipe_fd[i][1]);
}
free(pipe_fd);
return (NULL);
}
}
return (pipe_fd);
}
