### ISSUE TITLE
Bug with if & else

### ISSUE THREAD

**Issue by tonTed** [42School/norminette#236]
**Describe the bug**
The norminette accepts a bad indentation

**Erroneous code**
```
while (n--)
	if (*c_s != (unsigned char)c)
		c_s++;
else
	return (c_s);
```

**Additional infos**
 - OS: mac
 - python --version: Python 2.7.16
 - norminette -v: norminette 3.3.32

**Additional context**

**Comment by N0ich** [comment]
Hello, 
[this](https://github.com/42School/norminette/issues/121) [is](https://github.com/42School/norminette/issues/136) [still](https://github.com/42School/norminette/issues/190) [not](https://github.com/42School/norminette/issues/189) [a](https://github.com/42School/norminette/issues/149) [bug](https://github.com/42School/norminette/issues/149)[.](https://github.com/42School/norminette/issues/97)

Have a good day.
