### ISSUE TITLE
HEADER_PROT_NAME is always triggered on Windows OS.

### ISSUE THREAD

**Issue by PavelICS** [42School/norminette#244]
**Describe the bug**
When you check a project for norm on Windows it always triggers HEADER_PROT_NAME error for any .h file.
I program on Windows with CLion. And CLion configured to run project in the WSL. It's convinient for Windows users.
So it would be nice if norminette worked smothly on Windows too.

**Additional infos**
 - OS: Windows 10
 - python --version: 3.8.10
 - norminette -v: 3.3.40

**Additional context**
The probem in the different path seperators between Windows and Unix systems.
It's better to use patlhib library to parse filename or `os.path.basename` if you don't like this library.
```
from pathlib import Path
...

# target = target.split("/")[-1]
target = Path(target).name
...

# protection = context.filename.upper().split("/")[-1].replace(".", "_")
protection = Path(context.filename).name.upper().replace(".", "_")

```

**Comment by N0ich** [comment]
Hello,
For this kind of suggestions, it's easier with a pull request since you already identified the code you wanted to change.
I've done the changes and as far as I can tell, it works the same so i'm integrating them in the next release.

Thanks, have a great day
