### ISSUE TITLE
if statement without parenthesis

### ISSUE THREAD

**Issue by antikostya** [42School/norminette#245]
**Describe the bug**
if statement without parenthesis produces MULT_IN_SINGLE_INSTR error

**Erroneous code**
```c
int	main(void)
{
	int	i;

	if (i > 0)
		while (i)
		{
			i--;
		}
}
```
norminette return
```
Error: MULT_IN_SINGLE_INSTR (line:   7, col:   1):	Multiple instructions in single line control structure
```
#
**Additional infos**
 - OS: `Linuxmint 20.2 uma`
 - python --version: `Python 3.8.10`
 - norminette -v: `norminette 3.3.40`

**Comment by N0ich** [comment]
Hello,

Single line control structures should not have brackets when inside other single line control structure.
The proper way to write that down would be:
```
int	main(void)
{
	int	i;

	if (i > 0)
		while (i)
			i--;
}
```
