### ISSUE TITLE
string concatenation

### ISSUE THREAD

**Issue by antikostya** [42School/norminette#246]
**Describe the bug**
norminette does not allow string concatenation in header files

**Erroneous code**
if we try to define literal consisting two string - we getting an error
```c
#ifndef _H
# define _H

# define HELLO		"Hello, "
# define WORLD		"world!"

# define STRING1	"Hello, " "world!"
# define STRING2	HELLO "world!"
# define STRING3	"Hello, " WORLD
# define STRING4	HELLO WORLD

#endif
```
non of these ways are allowed
norminette return
```
Error: TOO_MANY_VALS        (line:   7, col:  27):	Too many values on define
Error: TOO_MANY_VALS        (line:   8, col:  23):	Too many values on define
Error: TOO_MANY_VALS        (line:   9, col:  31):	Too many values on define
Error: TOO_MANY_VALS        (line:  10, col:  27):	Too many values on define
```
#
### It also means, that there is no possibility to define large literals wich are longer than 67 characters
#
**Additional infos**
 - OS: `Linuxmint 20.2 uma`
 - python --version: `Python 3.8.10`
 - norminette -v: `norminette 3.3.40`

**Comment by N0ich** [comment]
Hello,
I can reenable basic string concat/maths in define stuff, but it's not up to me. 
That's a design choice by 42network so for now i won't reenable it.
I'll ask around
Have a good day
