### ISSUE TITLE
Allow preprocessor directives in c file - Or delete bonus rule ?

### ISSUE THREAD

**Issue by ggjulio** [42School/norminette#25]
> To turn in bonuses to your project, you must include a rule bonus to your Makefile,which will add all the various headers, librairies or functions that are forbidden onthe main part of the project. Bonuses must be in a different file_bonus.{c/h}.Mandatory and bonus part evaluation is done separately

Actually there is no way to respect the bonus rule. 
(Except for libft - libasm, but useless anyway because they're just libraries)
  
- Should preprocessor directives be allowed in c files ? 
- Or bonus rule should be deleted on all subjects ?

This rule confuse new students trying to go further than mandatory part.

https://stackoverflow.com/c/42network/questions/1624/1625

**Comment by N0ich** [comment]
Thank you for bringing that to our attention.

We will work towards a solution to fix that, we will keep you updated.
