### ISSUE TITLE
attributes at the begining of the line

### ISSUE THREAD

**Issue by antikostya** [42School/norminette#250]
**Describe the bug**
norminette does not allow attributes before declarators in .c files

**Erroneous code**
```c
__attribute__((__nothrow__)) int	main(void)
{
	return (0);
}
```
norminette return
```
Error: ATTR_EOL             (line:   1, col:   1):	Function attribute must be at the end of line
```
**but gcc does not allow attributes at the end of line in .c files**
#
**Additional infos**
 - OS: `Linuxmint 20.2 uma`
 - python --version: `Python 3.8.10`
 - norminette -v: `norminette 3.3.40`

**Comment by N0ich** [comment]
Hello,

I've muted the error for now, while we try to find a better solution.
