### ISSUE TITLE
Incorrect copyright notice in license file

### ISSUE THREAD

**Issue by Exagone313** [42School/norminette#26]
The `LICENSE` file contains this copyright notice:

```
Copyright (c) 2018 The Python Packaging Authority
```

But it doesn't reflect *norminette* authors.

**Comment by N0ich** [comment]
Im sorry but I believe this is expected.

How/what do you expect us to put there instead?

**Comment by vincentvis** [comment]
Looks like the MIT license
https://choosealicense.com/licenses/mit/

Which, unmodified, contains this line:

>Copyright (c) [year] [fullname]

To which you should do:

> Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders. 

I think Exagone313 is assuming that the license should be for Norminette, and thus signed with year and license holders of Norminette.
Now it is, instead, attributing the whole Norminette project to fall under the copyright of "The Python Packaging Authority".

---

Unless the "root" part of this project is forked from some python package thing. In which case you'd expect another license file in the "norminette" directory.

**Comment by N0ich** [comment]
Thanks a lot for the clarification.
I'll update the license with the next fixes.
