### ISSUE TITLE
Return value already with parenthesis, but "Return value must be in parenthesis"

### ISSUE THREAD

**Issue by caio-vinicius** [42School/norminette#262]
**Describe the bug**
The `return (1)` in the code below shows
Error: RETURN_PARENTHESIS   (line:  x, col:  x):	Return value must be in parenthesis
But, actually parenthesis are present, the semicolon is not.

**Erroneous code**
```c
int     ft_isspace(int c)
{
        if ((c >= 9 && c <= 13) || c == 32)
                return (1)
        return (0);
}       
```

**Additional infos**
 - OS: Ubuntu 20.04
 - python --version: 3.8.10
 - norminette -v: 3.3.51

**Additional context**
None

**Comment by LoisDuplain** [comment]
But this does not compile so i think it's not an issue, make your code compile first ^^

**Comment by vinicius507** [comment]
You're actually missing the `;` on the first return.

**Comment by caio-vinicius** [comment]
Yes, that's correct. Still the Norminette is outputing erroneous error.

**Comment by caio-vinicius** [comment]
So, I would tag this as a bug.

**Comment by jerem-ma** [comment]
I can't understand why you want to make the norminette show good messages if the file you are giving to the norminette does not compile. I think that the goal of norminette is to check norm errors on valid files so undefined behaviors on non-valid files would be ok. What would the norminette do if you give it this chapter below (It does not compile too, like your code) ? It makes no sense
https://en.wikisource.org/wiki/Alice%27s_Adventures_Under_Ground/Chapter_1

**Comment by caio-vinicius** [comment]
Well, let's take another famous linter as a example:

```python
def test():
    print("asasa"
```

This is Python 3 code, which will not "compile" because there's a parenthesis not in the right place. If we try:

```bash
  File "test.py", line 3
    
                     ^
SyntaxError: unexpected EOF while parsing
```

Yeah, seems like you cannot run this code.

Now, pass this code to the flake8 linter:

```bash
test.py:2:17: E999 SyntaxError: unexpected EOF while parsing
```

Concise error return, showing that the parsing cannot be done, due to something unexpected.

The point is: the linter needs to show concise messages, otherwise it's showing wrong output. There's no need to show good messages about like "put semicolon here", but needs to be concise with what's happening.

**Comment by jerem-ma** [comment]
I understand what you are saying. It is true that saying bad information could be confusing. It could be interesting to correct these error messages from the norminette. It remains to be seen the time that would take this correction. An alternative solution could be saying that only c files that pass c linter should be passed to the norminette or undefined behavior will occur.

**Comment by N0ich** [comment]
I'm sorry but this debate is out of scope for now. While I agree the norminette linter work could be better, this is unfortunately not something anybody is working on atm

Thank you for the report and the discussion :)
