### ISSUE TITLE
Missing space after operator error being issued instead of extra space.

### ISSUE THREAD

**Issue by HcDuller** [42School/norminette#263]
this is the correct expression:
"while (i > -1)"

If this expression is replaced by:
"while (i > - 1)"
 (there is now a space between '-' and '1')
"Error: SPC_AFTER_OPERATOR   (line:  x, col: 17):      missing space after operator" is issued.

if i insert another space, making it:
"while (i >  - 1)" 
Then i get :
"Error: CONSECUTIVE_SPC      (line:  y, col:  16):      Two or more consecutives spaces"
"Error: SPC_AFTER_OPERATOR   (line:  y, col:  18):      missing space after operator"

**Comment by N0ich** [comment]
I can't seem to reproduce this error. What is your version, and can I get backquoted code that gives this error specifically?

**Comment by HcDuller** [comment]
> I can't seem to reproduce this error. What is your version, and can I get backquoted code that gives this error specifically?

Its not happening anymore.
