### ISSUE TITLE
Error: Code ended unexpectedly.

### ISSUE THREAD

**Issue by MisterTooh** [42School/norminette#264]
**Describe the bug**
If a **space is placed** at the **end of the file after the mandatory new line**, **all other norm errors are ignored** and this message appears:
"Error: Code ended unexpectedly."

**Erroneous code**
```C
#include <stdio.h>

int main(void)
{
    printf("Hello World!"); 
    return (0);
}
/*<-- add space here.
All norm errors on the 
file will be ignored,
and above mentioned message 
is returned by norminette */
```

**Additional infos**
 - OS: macOS Catalina Version 10.15.7
 - python --version: 2.7.16
 - python3 --version: 3.9.7
 - norminette -v: 3.3.32

**Additional context**
To recreate this error see Erroneous code.
main.c: Error!
        Error: Code ended unexpectedly.

<img width="343" alt="Screen Shot 2021-11-27 at 3 35 02 PM" src="https://user-images.githubusercontent.com/55613401/143680133-c7863cac-e8f3-4888-918f-aa016d3b7670.png">

**Comment by N0ich** [comment]
Fixed as of 3.3.51
