### ISSUE TITLE
Incorrect column offset for col = 0

### ISSUE THREAD

**Issue by GlaceCoding** [42School/norminette#266]
**Describe the bug**
When we have an error on the beginning of the line `col: 0`, norminette returns `col: 1`.

**Erroneous code**
```c
// <--- here error on the second `/` with offset 1
//23456789012345678901234567890 

//  v offset = 4
int a(void)
{
 
}
static int b(int c)
{
}
```

**norminette:**

```c
Error: INVALID_HEADER       (line:   1, col:   1):	Missing or invalid 42 header
Error: SPACE_BEFORE_FUNC    (line:   5, col:   4):	space before function name
Error: EMPTY_LINE_FUNCTION  (line:   7, col:   1):	Empty line in function
Error: SPACE_EMPTY_LINE     (line:   7, col:   1):	Space on empty line
Error: NEWLINE_PRECEDES_FUNC (line:   9, col:   1):	Functions must be separated by a newline
Error: SPACE_BEFORE_FUNC    (line:   9, col:  11):	space before function name
```

**expected output:**
We should expect `col: 0` for: `INVALID_HEADER`, `EMPTY_LINE_FUNCTION` and `NEWLINE_PRECEDES_FUNC`.

<details>
  <summary>Spoiler : Expected output</summary>

```c
Error: INVALID_HEADER       (line:   1, col:   0):	Missing or invalid 42 header
[...]
Error: EMPTY_LINE_FUNCTION  (line:   7, col:   0):	Empty line in function
Error: SPACE_EMPTY_LINE     (line:   7, col:   0):	Space on empty line
Error: NEWLINE_PRECEDES_FUNC (line:   9, col:   0):	Functions must be separated by a newline
[...]
```
</details>

**Additional infos**
 - OS: Mojave 10.14.6
 - python --version: Python 2.7.16
 - norminette -v: norminette 3.3.51

**Additional context**
I use a plugin linter on my code editor which extract the column on norminette output, but I got a weird result because norminette output returns a wrong col with error on the beginning of the line (col = 1 instead of 0) .

<details>
  <summary>Spoiler : Visual linter on norminette output</summary>

![Screen Shot 2021-11-29 at 2 24 10 PM](https://user-images.githubusercontent.com/92152391/143876200-40fc31d6-5853-4668-b20f-e5755eff2343.png)
</details>

**Comment by N0ich** [comment]
Hello,
It looks like the first position the tokenizer takes is the column n1. While it COULD make more sense to use col 0 as a starter, it would also be logic to use 0 as the first line. 
However, code editors start counting at line 1 and it would probably confuse people. As a personal note, my code editor consider the first column to be col 1.

I can change that, but I'm not sure I would recommend it.

**Comment by GlaceCoding** [comment]
If we start at the offset `1` then we need to increment each error of one to get the good column

**Comment by N0ich** [comment]
Well I think that's already what it does. I haven't used myself a norminette linter but I've seen a few around and if you consider the first column to be 1 (just as lines) it works perfectly.

**Comment by GlaceCoding** [comment]
I recalculated manually with my hand and not with the lib of my hightligther it works perfectly, thanks for your time 😅. ~~I just saw it was the lib that changes the offset if the line got a tab~~
