### ISSUE TITLE
MULT_IN_SINGLE_INSTR error

### ISSUE THREAD

**Issue by mohamedbouzaien** [42School/norminette#267]
I'm having a "Multiple instructions in single line control structure" while i don't have multiple instructions in one line in my code, i increment my iterator inside my loop, but when i increment it inside the while instrcution the error desappears!
I think it is doing the opposite of what it should do.

Here is my code:
`/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_memmove.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mbouzaie <mbouzaie@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/12/04 15:44:02 by mbouzaie          #+#    #+#             */
/*   Updated: 2020/05/12 18:54:10 by mbouzaie         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "includes/libft.h"

void	*ft_memmove(void *dst, const void *src, size_t n)
{
	char	*d;
	char	*s;
	size_t	i;

	if (!dst && !src)
		return (NULL);
	i = 0;
	d = (char *)dst;
	s = (char *)src;
	if (d < s)
		while (i < n)
		{
			d[i] = s[i];
			i++;
		}
	else
		while (n > 0)
		{
			n--;
			d[n] = s[n];
		}
	return (dst);
}
`
and here is the error log:
`srcs/libft/ft_memmove.c: Error!
Error: MULT_IN_SINGLE_INSTR (line:  28, col:   1):      Multiple instructions in single line control structure
Error: MULT_IN_SINGLE_INSTR (line:  34, col:   1):      Multiple instructions in single line control structure`

**Comment by c3b5aw** [comment]
You have to put braces around your while loops and you should do it every time you have more than one line under a condition, at least for clarity.
view : https://google.github.io/styleguide/cppguide.html#Loops_and_Switch_Statements

This is your code fixed.

```
if (d < s)
{
	while (i < n)
	{
		d[i] = s[i];
		i++;
	}
}
else
{
	while (n > 0)
	{
		n--;
		d[n] = s[n];
	}
}
```

If you want to shorten your code, you could use, for example, the following snippet. 
There are several variations, look at pre/post-increment on your favorite search engine.

```
int i = -1;
if (d < s)
	while (++i < n)
		d[i] = s[i];
else
	while (--n > 0)
		d[n] = s[n];
```

**Comment by N0ich** [comment]
Thank you, closing this issue.
