### ISSUE TITLE
Allow globals that are marked const and static

### ISSUE THREAD

**Issue by fifididi** [42School/norminette#27]
There is no reason to disallow globals that are immutable and static. 

For example, If a student wants to create a lookup table that is bigger than what a function would allow, then it's impossible to do without having to waste computational resources.

**Comment by N0ich** [comment]
Hello,
After testing I can't seem to reproduce what you're talking about. 
Can you include an example?

**Comment by abaurens** [comment]
I can totally relate to that. But it's more a question about the norme itself than about the norminette.

The point is that globals are generally not allowed. wich makes no sense when they are both static and constants.
Those kind of variables are almost the only option we have to build clean and effective loockup tables.

i can take my printf's conversion lookup table as an example:
```C
static const t_converter	g_converters[] =
{
	{'%', FALSE, ARG_NON, convert_percent},
	{'d', TRUE, ARG_INT, convert_integer},
	{'D', TRUE, ARG_INT, convert_linteger},
	{'i', TRUE, ARG_INT, convert_integer},
	{'u', TRUE, ARG_INT, convert_u_integer},
	{'U', TRUE, ARG_INT, convert_u_linteger},
	{'o', TRUE, ARG_INT, convert_u_integer_octal},
	{'O', TRUE, ARG_INT, convert_u_linteger_octal},
	{'x', TRUE, ARG_INT, convert_u_integer_hexa},
	{'X', TRUE, ARG_INT, convert_u_integer_hexa},
	{'f', TRUE, ARG_FLT, convert_double_floating},
	{'F', TRUE, ARG_FLT, convert_double_floating},
	{'e', TRUE, ARG_FLT, convert_double_scientific},
	{'E', TRUE, ARG_FLT, convert_double_scientific},
	{'g', TRUE, ARG_FLT, convert_double_compact},
	{'G', TRUE, ARG_FLT, convert_double_compact},
	{'a', TRUE, ARG_FLT, convert_double_hexa},
	{'A', TRUE, ARG_FLT, convert_double_hexa},
	{'c', TRUE, ARG_INT, convert_char},
	{'C', TRUE, ARG_INT, convert_wchar},
	{'s', TRUE, ARG_PTR, convert_string},
	{'S', TRUE, ARG_PTR, convert_wstring},
	{'p', TRUE, ARG_PTR, convert_pointer},
	{'n', TRUE, ARG_PTR, convert_length},
	{'b', TRUE, ARG_INT, convert_u_integer_binary},
	{'r', TRUE, ARG_PTR, convert_non_printable_string},
	{'R', TRUE, ARG_INT, convert_non_printable_char},
	{'m', FALSE, ARG_NON, convert_strerror},
	{'k', TRUE, ARG_INT, convert_iso_date},
	{'\0', MAYBE, ARG_NON, (void *)0x0}
};
```
Building such a table any other way would be both stupid and wastefull...

**Comment by fifididi** [comment]
@N0ich The norminette doesn't seem to trigger an error for correctly formatted lookup tables, The norm, however, mentions that global variables are forbidden unless allowed explicitly. 

Seeing that the norminette isn't deployed yet, it is unsure for students that this rule will be implemented into the norminette or not. If it's the case, this issues asks for the removal of that rule. If not, then a simple change on the norm's pdf saying that const+static globals are ok would help elevate the confusion of other students when they see globals passing the norminette during corrections.

**Comment by N0ich** [comment]
Hello,
Thank you for your contribution.

We will rephrase the norme itself to allow for const static global variables, however those must still be justified.

**Comment by fifididi** [comment]
Hello, I see changes to the PDFs and tex files are being made but this issue has yet to be resolved.

If you need help with the wording, I would suggest changing the global variable rule to something like the following: 
"Using global variables that are not marked const and static is forbidden and is considered a norm error, unless the project explicitly allows them."

Thank you and have a nice day.

**Comment by fifididi** [comment]
@N0ich 👋

**Comment by N0ich** [comment]
Hello, you can reopen the ticket when adding comments like that, makes it easier to see, i missed your previous comment :)
Reopening, will add said wording.

**Comment by fifididi** [comment]
I'm sorry but I couldn't re-open the issue, otherwise I would have done it. I think it has to do with being a repo collaborator or contributor.. Thank you for re-opening it!
