### ISSUE TITLE
Impossible to install norminette on new mac

### ISSUE THREAD

**Issue by vessfils** [42School/norminette#275]
**Describe the bug**
I installed python 3.7.9 and I executed the 2 lines but the norminette is not working. 
When I'm doing which pyton this is the result ==> /usr/bin/python.

I try to install with homebrew or pyenv but this. If you have any idead =0

**Erroneous code**
Please use markdown to send the code here.

**Additional infos**
 - OS:Monterey
 - python --version:3.7.9
 - norminette -v:

**Additional context**

**Comment by yace1** [comment]
I have the same issue

**Comment by N0ich** [comment]
Hello, please use slack and send a full error log for the part where `the norminette is not working`
