### ISSUE TITLE
Allow constant values in defines

### ISSUE THREAD

**Issue by fifididi** [42School/norminette#282]
**Describe the bug**
Constant values that result from compile-time evaluations are not considered constant in defines.

The below code breaks the PREPROC_CONSTANT rule.

**Erroneous code**
```c
/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   header.h                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: xxxxxxxx <xxxxxxxx@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/01/20 03:06:33 by xxxxxxxx          #+#    #+#             */
/*   Updated: 2022/01/20 03:07:15 by xxxxxxxx         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef HEADER_H
# define HEADER_H

# define WORD_SIZE (sizeof(unsigned long int))

#endif
```

**Additional infos**
 - norminette -v: 3.3.51

**NOTE**

I'm well aware that this feature has been neglected in the past ( #127 ) but there is no reason for the norminette to:

1. Report false information, (compile-time evaluations are constant).
2. Make life harder for students that are actively trying to write **readable** code (which is the purpose of the norm, if I'm not mistaken?). Defines create symbols that help contextualise magic numbers, remove bloat from complex expressions, or in this case, help the reader having a clear idea of what the evaluation stands for and therefore improves code readability.

**WHAT CAN STUDENTS DO ABOUT THIS?**

Part of the reason I'm creating this issue is to give students that would want this bug to be a fixed a solution.
Under 3.3.51, you can use enums to bypass this error:
```c
/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   header.h                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: xxxxxxxx <xxxxxxxx@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/01/20 03:06:33 by xxxxxxxx          #+#    #+#             */
/*   Updated: 2022/01/20 03:16:29 by xxxxxxxx         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef HEADER_H
# define HEADER_H

enum e_word_size {
	WORD_SIZE = sizeof(unsigned long int)
};

#endif

```
Which is in essence, the same thing as defining the WORD_SIZE symbole through a `#define`.
Of course, students that know python and are willing to contribute to this project can also make a pull request to fix this bug.

**Comment by mjy9088** [comment]
`:+1:` for use enum, and I wanna introduce `int64_t` in `<stdint.h>`

**Comment by matthieu42Network** [comment]
Hello, Pre-processing and compile time are 2 different things. The norme only accept pre-processing constant :)
