### ISSUE TITLE
Global variable notice disappears if norm is OK

### ISSUE THREAD

**Issue by Mazoise** [42School/norminette#287]
**Describe the bug**

The notice for global variables only appears if there is a norm error in the file. Otherwise it displays "OK!"

**Erroneous code**

> ../xxx.c: Error!
> Notice: GLOBAL_VAR_DETECTED  (line:  13, col:   1):     Global variable present in file. Make sure it is a reasonable choice.
> Error: GLOBAL_VAR_NAMING    (line:  13, col:   9):      Global variable must start with g_

\*\*\* added "g_" to resolve norm error \*\*\*
> ../xxx.c: OK!

**Additional infos**
 - OS: dump linux (42 paris)
 - python --version: Python 2.7.18 (python3 : Python 3.8.10)
 - norminette -v: norminette 3.3.50

**Comment by Guillaume1868** [comment]
Wanted to report this bug but this issue is already opened, still hapening in 3.3.51
