### ISSUE TITLE
`const` in return function pointer declaration requires extra tab

### ISSUE THREAD

**Issue by D4ryl00** [42School/norminette#29]
In a header file, a function declaration like this:
`const char *func(void);`

requires a tab after `const` although a space is expected. The only tab required must be after `char`.

EDIT:
The actual code is: `const char *(*func)(void);`
The error is:
`SPACE_REPLACE_TAB    (line:  16, col:   6):     Found space when expecting tab`

**Comment by N0ich** [comment]
Hello, 

I can't seem to reproduce it. The norminette returns me no error (as expected) when you put a tab after char and a space after const.

**Comment by D4ryl00** [comment]
Ok sorry for the example above, it's wrong. It's with a function pointer that the error appears:
`const char  *(*func)(void);`

**Comment by D4ryl00** [comment]
I've updated the issue.
