### ISSUE TITLE
Cannot make norminette say "OK!" when I use enum

### ISSUE THREAD

**Issue by xvoorvaa** [42School/norminette#295]
**Describe the bug**
After I create a `enum` and directly afterward a `typedef struct`, I cannot make norminette say "OK!".

**Erroneous code**
How it should be:
```
#ifndef BUG_H
# define BUG_H

enum e_token {
	T_UNKNOWN,
	T_LITERAL,
	T_LITERAL_EXPANDING,
	T_LITERAL_NONEXPANDING,
	T_PIPE,
	T_REDIRECT_STDOUT_TO_FILE, /* > */
	T_REDIRECT_STDOUT_TO_FILE_APPEND, /* >> */
	T_REDIRECT_FILE_TO_STDIN, /* < */
	T_REDIRECT_FILE_TO_DELIMITER /* << */
};

typedef struct s_token
{
	char			*content;
	int				separated_from_previous;
	enum e_token	token;
	struct s_token	*next;
}	t_token;

#endif
```

What norminette says is almost "OK!":
```
#ifndef BUG_H
# define BUG_H

enum e_token {
	T_UNKNOWN,
	T_LITERAL,
	T_LITERAL_EXPANDING,
	T_LITERAL_NONEXPANDING,
	T_PIPE,
	T_REDIRECT_STDOUT_TO_FILE, /* > */
	T_REDIRECT_STDOUT_TO_FILE_APPEND, /* >> */
	T_REDIRECT_FILE_TO_STDIN, /* < */
	T_REDIRECT_FILE_TO_DELIMITER /* << */
};
	typedef struct s_token
{
	char *content;
	int separated_from_previous;
	enum e_token token;
	struct s_token *next;
}	t_token;

#endif


```
**Additional infos**
 - OS: MacOS Mojave 10.14.6
 - python --version: 2.7.16
 - norminette -v: 3.3.51

**Additional context**
It is impossible to make this "OK!" with norminette. I cannot finish my project without removing the `enum`.

**Comment by vincentvis** [comment]
Seems to work fine here. What are the norm errors you're getting?
(I'm assuming you are adding the 42/codam header. And that you are removing the comments from inside the enum, since they are invalid in that scope)
