### ISSUE TITLE
Impossible to put function prototype exceeding 81 characters in headerfile

### ISSUE THREAD

**Issue by Tishj** [42School/norminette#30]
Either "line too long"
or "unrecognized variable type" when splitting the prototype over multiple lines

example that results in "unrecognized variable type":
```
void                get_draw_info(t_draw *draw, double perpwalldist,
                                    t_texture texture[4], t_mov mov);
```

example that results in "line too long":
```
void                get_draw_info(t_draw *draw, double perpwalldist, t_texture texture[4], t_mov mov);
```

Is there another way to put this prototype into my header in a norm-compliant way?

**Comment by vincentvis** [comment]
if you put the comma on the next line it works...

```
void				get_draw_info(t_draw *draw, double perpwalldist
								, t_texture texture[4], t_mov mov);
```

Although I really hope this isn't going to be the "official" new way and this will be fixed...
