### ISSUE TITLE
Missing tabs for indent level when assign boolean statement to a variable

### ISSUE THREAD

**Issue by LuigiEnzoFerrari** [42School/norminette#300]
**Describe the bug**
Missing tabs for indent level when assign two or more boolean expressions to a variable

**Erroneous code**
```c
static void	test(int a, int b, int c)
{
	a = c != 0 || c != 5;
}
```

**Additional infos**
 - OS: 20.04.4 LTS
 - python --version: 3.8.10
 - norminette -v: 3.3.51

**Additional context**
```sh
Error: TOO_FEW_TAB          (line:  15, col:  19):	Missing tabs for indent level
```

**Comment by matthieu42Network** [comment]
fixed in 3.3.52
