### ISSUE TITLE
Norminette 3.3.51 crash on header files

### ISSUE THREAD

**Issue by Jkutkut** [42School/norminette#307]
## Description:
Crash when checking .h files with invalid header protection and define as the last instruction inside the if statement.

## Example:
The full example can be found on [this repository](https://github.com/Jkutkut/Norminette-3.3.51-Possible_bug).

Norminette crashes when it finds a `file.h` with an invalid header protection name and the last sentence on the if statement is a declare (with an include it does work).

	/* ************************************************************************** */
	/*                                                                            */
	/*                                                        :::      ::::::::   */
	/*   doesnt_work_incorrect.h                            :+:      :+:    :+:   */
	/*                                                    +:+ +:+         +:+     */
	/*   By: jre-gonz <jre-gonz@student.42madrid.com    +#+  +:+       +#+        */
	/*                                                +#+#+#+#+#+   +#+           */
	/*   Created: 2022/04/12 11:43:41 by jre-gonz          #+#    #+#             */
	/*   Updated: 2022/04/12 12:23:34 by jre-gonz         ###   ########.fr       */
	/*                                                                            */
	/* ************************************************************************** */

	#ifndef DOESNT_WORK_INCORRECT
	# define DOESNT_WORK_INCORRECT

	# define TEST "this is a test"

	#endif

## Tested versions:
- Mac OS (42Madrid):
  - norminette 3.3.51
  - python 3.7.3
- Ubuntu 21.10:
  - norminette 3.3.51 and repository in current [commit](https://github.com/42School/norminette/commit/d443df72accb7b66bd65e98d76207da1e6968e00).
  - python 3.9.2
- Debian GNU/Linux 11.
  - norminette 3.3.51
  - python 3.9.2

## Example error Mac OS:

	$> norminette include/doesnt_work_incorrect.h
	Traceback (most recent call last):
	File "/usr/local/bin/norminette", line 8, in <module>
		sys.exit(main())
	File "/Library/Python/3.7/site-packages/norminette/__main__.py", line 121, in main
		registry.run(context, source)
	File "/Library/Python/3.7/site-packages/norminette/registry.py", line 65, in run
		ret, jump = self.run_rules(context, rule)
	File "/Library/Python/3.7/site-packages/norminette/registry.py", line 43, in run_rules
		self.run_rules(context, self.rules[r])
	File "/Library/Python/3.7/site-packages/norminette/registry.py", line 32, in run_rules
		rule.run(context)
	File "/Library/Python/3.7/site-packages/norminette/rules/check_preprocessor_define.py", line 127, in run
		context.new_error("HEADER_PROT_ALL_2", context.peek_token(i))
	File "/Library/Python/3.7/site-packages/norminette/context.py", line 204, in new_error
		self.errors.append(NormError(errno, tkn.pos[0], tkn.pos[1]))
	AttributeError: 'NoneType' object has no attribute 'pos'

**Comment by matthieu42Network** [comment]
fixed in 3.3.52
