### ISSUE TITLE
A file that contains only one number

### ISSUE THREAD

**Issue by llirrikk** [42School/norminette#308]
**Describe the bug**
Norminette is wrong when file that contains only one number.

**Erroneous code**
- I am trying to check `file.c` which contains only number without trailing newline:
```bash
echo -n "12345" > file.c
norminette file.c
```
And got norminette's response:
```bash
0
file.c: OK!
```

- If I run norminette with `-dd` flag:
```bash
norminette -dd file.c
```
There is the result:
```bash
2
uncaught -> [<CONSTANT=12345>]
file.c: OK!
```

**Additional infos**
 - OS: Linux Mint 20.3
 - python --version: Python 3.8.10
 - norminette -v: norminette 3.3.51

**Additional context**
In the first case, I get the number `0` and the inscription that the file is `OK`. In the second case, the number `2` appears, followed by `OK`.

I think the file in this case should not correspond to the norminette, especially uninformative output such as `0` and `2`.

**Comment by matthieu42Network** [comment]
Hello, `The file must compile. A file that doesn’t compile isn’t expected to pass the Norm.`
