### ISSUE TITLE
Function pointer error when return type is not standard and more than one parameter in prototype

### ISSUE THREAD

**Issue by oddtiming** [42School/norminette#312]
**Describe the bug**
I was getting a norminette error `Error: Unrecognized line (35, 37) while parsing line [<INT>, <RPARENTHESIS>]` while declaring some function pointers, but not others. The bug disappears when I reduce the function pointers parameters, or when I change the return type. It seems to be an error in parsing. 
<img width="600" alt="Capture d’écran, le 2022-05-01 à 16 30 45" src="https://user-images.githubusercontent.com/36460419/166163471-cd72c4a1-61ee-4fd8-9fac-65e1ad766f6b.png">

**Erroneous code**
- The line in question :
```c
	bool	(*add_front)(t_deque *, int);
```

- The full struct:
<img width="408" alt="Capture d’écran, le 2022-05-01 à 16 30 35" src="https://user-images.githubusercontent.com/36460419/166163499-ac1a9097-473a-45ad-b638-ddfeab7d9f82.png">

- The possible fixes:
```c
	bool	(*add_front)(t_deque *);
```
```c
	int	(*add_front)(t_deque *, int);
```

**Additional infos**
 - OS: MacOS Catalina 10.15.7
 - python --version:  2.7.16
 - norminette -v: 3.3.51

**Comment by pnuts93** [comment]
I am having the same issue, perhaps it may be useful if I write what I did as well.  
In case I declare an array of pointers to functions like this:  
`int (*f[3])(int, char*)`  
Norminette does not raise any issue, however, if I declare something similar, just with a non-primitive return value like this:  
`t_mystruct (*f[3])(int, char*)`  
Norminette will raise an error. I am attaching the screenshots as well.  
![Screenshot from 2022-05-09 08-54-36](https://user-images.githubusercontent.com/61493084/167667691-796f8972-2fe7-427b-bdf1-157bf58ade39.png)
![Screenshot from 2022-05-09 08-54-57](https://user-images.githubusercontent.com/61493084/167667698-399b010e-c729-4d99-8914-7155a839b04b.png)
![Screenshot from 2022-05-09 08-55-30](https://user-images.githubusercontent.com/61493084/167667700-be6a633d-499d-4889-8a8a-575088de4c59.png)
![Screenshot from 2022-05-09 08-55-39](https://user-images.githubusercontent.com/61493084/167667702-83b80bd6-c6c9-4ae0-b898-7a1e5a2af1fa.png)
  
- Norminette -v: 3.3.51  
- Python --version: 3.8.10
- OS Ubuntu 20.04.1

**Comment by Akronae** [comment]
Same for me.  It's really a pain. https://github.com/42School/norminette/issues/332

**Comment by matthieu42Network** [comment]
Hello, can't reproduce the original issue. please reopen the issue with better example if needed.
