### ISSUE TITLE
Norminette crash if there is a tab/space in the last line.

### ISSUE THREAD

**Issue by PepeSegura** [42School/norminette#354]
**Describe the bug**
Norminette crash if there is a tab/space in the last line.
<img width="716" alt="Screen Shot 2022-10-11 at 12 03 48 AM" src="https://user-images.githubusercontent.com/37574170/194959221-22c5f444-fafe-40ba-a7c0-c20dc8e67652.png">
<img width="380" alt="Screen Shot 2022-10-10 at 11 58 41 PM" src="https://user-images.githubusercontent.com/37574170/194958601-99466e8e-9eb6-4d8b-a96d-7893440ade8a.png">

**Erroneous code**
Repo with a file that breaks norminette
[https://github.com/PepeSegura/Norminette-broken](url)

**Additional infos**

**Additional context**
Bug happens in .c and .h files

**Comment by matthieu42Network** [comment]
fixed in 3.3.52
