### ISSUE TITLE
Too many values on define in header file

### ISSUE THREAD

**Issue by nach131** [42School/norminette#357]
**Describe the bug**

in the header file declare, four ERROR with value of one bit

```c
20 # define ERROR_0 1 << 0
21 # define ERROR_1 1 << 1
22 # define ERROR_2 1 << 2
23 # define ERROR_3 1 << 3
```

**Erroneous code**

```
Error: TOO_MANY_VALS        (line:  20, col:  34):	Too many values on define
Error: TOO_MANY_VALS        (line:  21, col:  35):	Too many values on define
Error: TOO_MANY_VALS        (line:  22, col:  36):	Too many values on define
Error: TOO_MANY_VALS        (line:  23, col:  37):	Too many values on define
```

**Additional infos**

 - OS: macOS 10.13.6
 - python --version: 2.7.16
 - norminette -v: 3.3.51

**Additional context**
not relevant

**Comment by nuoxoxo** [comment]
Can you write it this way? It passes the norm.
```
#define ERROR_0 1
#define ERROR_1 2
#define ERROR_2 4
#define ERROR_3 8
```
Unless you have other ways to avoid another error which is <kbd> Preprocessor statement must only contain constant defines </kbd>
