### ISSUE TITLE
Norminette check function name from external library.

### ISSUE THREAD

**Issue by ggjulio** [42School/norminette#36]
It seem the new norminette check function name not only at declaration and definition, but also at every single line.
Causing problems when using functions from libraries that don't use our naming convention.

```
sound_management.c: KO!
        FORBIDDEN_CHAR_NAME  (line: 24, col: 15):       user defined identifiers should contain only lowercase characters, digits or '_'
        FORBIDDEN_CHAR_NAME   (line: 38, col: 5):       user defined identifiers should contain only lowercase characters, digits or '_'
        FORBIDDEN_CHAR_NAME   (line: 52, col: 5):       user defined identifiers should contain only lowercase characters, digits or '_'
```

```c
void	destroy_sound(t_sound to_destroy)
{
	free(to_destroy.filename);
	FMOD_Sound_Release(to_destroy.ptr);
}
```
Would it be better if the norminette check names only in prototypes and definitions ?

**Comment by N0ich** [comment]
Hello, 
Which version are you using? I've disabled thiese checks in the last update.

**Comment by ggjulio** [comment]
My bad, I was not using the last version. It works on 3.0.2
