### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by isabel42** [42School/norminette#360]
Command not found. 
I have installed norminette, everything seemed fine but when trying to launch it in a project, the terminal cannot find the command "norminette". Thanks.

**Comment by LeonPupier** [comment]
Hello ;)
For you to be able to call "norminette" easily you must first add the command to the **PATH**. This is done in several ways, here is one:
1. You have to edit the following file in a terminal:
```sudo nano .bashrc```
2. Add this line at the end of the file:
```export PATH="$HOME/.local/bin:$PATH"```
3. Finally, update the environment script:
```source .bashrc```


**[OPTIONAL]**
-> If you use "zsh" the handling changes slightly...
1. You have to edit the following file in a terminal:
```sudo nano .zshrc```
2. Add this line at the end of the file:
```export PATH="$HOME/.local/bin:$PATH"```
3. Finally, update the environment script:
```source .zshrc```

Hope that answered your question!
Have a good day,
*Léon*

**Comment by isabel42** [comment]
Hello Léon, 

Thank you for your help, though this is still not working :(
Norminette is installed within the following directory : Library/Phyton/3.9/ in mac environnement. 
What I found is that I can perfectly launch it via python3 -m norminette. However in order to use Francinette, I need to make the command norminette work. 

Thank you in advance for your further support.

**Comment by LeonPupier** [comment]
Hello again Isabel,

In case you are on MAC, I think you can just edit the following file:
```~/.profile```
To add this line at the end of the file:
```PATH=$PATH:~/Library/Python/3.9/``` *(or maybe ```PATH=$PATH:~/Library/Python/3.9/bin/```)*
Then close and relaunch a new terminal.

An alternative method that I haven't been able to test would be to edit the following file if it exists for you:
```/etc/path```
And add this line at the end of the file:
```Library/Python/3.9/```

Unfortunately, I have no other solution to offer you, hoping that these will work...
Have a great day and good luck,
*Léon*

**Comment by isabel42** [comment]
Hello, 

Getting inspired in your reply and some other inputs, I tried inserting the following alias on .zshrc file following steps on [OPTIONAL] in your first reply

alias norminette=/Users/isabeltovar/Library/Python/3.9/bin/norminette

It works now for the command norminette! Next step is making it work when calling francinette :) (I have opened a new issue in francinette). 

Thank you!

**Comment by LeonPupier** [comment]
This is actually a very good idea! All the better if everything is working now.
Have a good day !
*Léon*

**Comment by isabel42** [comment]
Even better! 
I wrote at the end of the file

export PATH="/Users/isabeltovar/Library/Python/3.9/bin:$PATH"

Francinette and norminette work now! 
Thank you
