### ISSUE TITLE
Norminette program escape * with a \. And stop flag every norm error.

### ISSUE THREAD

**Issue by lseiller** [42School/norminette#362]
**Describe the bug**
If you make a comment like this: `/**/` but add a backslash between the two `*`, the norminette considers that everything below is inside a comment.

**Erroneous code**
```c
/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: lseiller <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/12/08 14:17:47 by lseiller          #+#    #+#             */
/*   Updated: 2022/12/08 14:19:36 by lseiller         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <unistd.h>

/*\*/
int	main()
{
	for (int i = 0; i < 10; i++)
		write(1, "42\n", 3);
	return (0);
}
/**/
```

**Additional infos**
 - OS: Ubuntu 22.04.1 LTS
 - python --version: Python 3.10.8
 - norminette -v: norminette 3.3.51

**Additional context**
The norminette should tell us that using a `for` control structure is forbidden. But the norminette doesn't report an error and tells us that everything is OK.
Since everything between `/*\*/` is ignore by norminette, student could use that to avoid everything in the 42 norm.
In correction it can be quite visible, if he use `for` loops, switch case etc. For the rest, it's hard to see with the our eye the rows spending 80 in columns, the functions with more than 25 line, aso...

**Comment by matthieu42Network** [comment]
duplicate #293
