### ISSUE TITLE
error when define colors in .h

### ISSUE THREAD

**Issue by amonbaro** [42School/norminette#378]
Programme is working and all other files are norm -> OK

<img width="789" alt="Screen Shot 2023-06-01 at 1 26 03 PM" src="https://github.com/42School/norminette/assets/116653382/e5c2ee50-6569-45bc-9321-d30ba5bdd70f">
<img width="693" alt="Screen Shot 2023-06-01 at 1 40 47 PM" src="https://github.com/42School/norminette/assets/116653382/d9d50420-c63a-413c-aacc-1c58a41dfc7c">

Problem solved by removing the colors but it might be a good update to make it work

**Comment by matthieu42Network** [comment]
fixed in 3.3.52
