### ISSUE TITLE
t_map *map SPC_BFR_OPERATOR and SPC_AFTER_OPERATOR

### ISSUE THREAD

**Issue by GitCGuillaume** [42School/norminette#38]
Hello,
The norminette-beta v3 on guacamole is displaying :
```
int render_map(void *param)
{
    int     endian;
    t_map   *map;   <<<< error is here

endian = 0;
    map = (t_map *)param;
```

And it display 

```
SPC_BFR_OPERATOR (line: 18, col: 13):missing space before operator
SPC_AFTER_OPERATOR (line: 18, col: 13):missing space after operator
```
I don't have this issue with the norminette v2.

**Comment by GitCGuillaume** [comment]
Look like i've found my issue but in the pdf norm v3 it's still written "The asterisks that go with pointers must be stuck to variable names."

    t_map    *  map;

**Comment by N0ich** [comment]
Yep, I will fix it in the next update. Thanks for the issue

**Comment by N0ich** [comment]
It has actually been fixed. Make sure you are using the correct norminette version (current 3.0.2) or check with the staff to update it in your campus. 
Thanks for the issue nonetheless
