### ISSUE TITLE
Exception when #include is not followed by a space

### ISSUE THREAD

**Issue by pruiz-ca** [42School/norminette#383]
**Describe the bug**
When the #include is not followed by a space norminette throws an exception

**Erroneous code**
Having a test.c file with `#include<unistd.h>` throws the following error:

> Traceback (most recent call last):
>   File "/usr/local/bin/norminette", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/norminette/__main__.py", line 128, in main
>     registry.run(context, source)
>   File "/usr/local/lib/python3.10/dist-packages/norminette/registry.py", line 65, in run
>     ret, jump = self.run_rules(context, rule)
>   File "/usr/local/lib/python3.10/dist-packages/norminette/registry.py", line 43, in run_rules
>     self.run_rules(context, self.rules[r])
>   File "/usr/local/lib/python3.10/dist-packages/norminette/registry.py", line 32, in run_rules
>     rule.run(context)
>   File "/usr/local/lib/python3.10/dist-packages/norminette/rules/check_preprocessor_include.py", line 47, in run
>     while tkns[i].type != "NEWLINE" and i < len(tkns) - 1:
> IndexError: list index out of range

**Additional infos**
 - OS: Ubuntu 22.04.1
 - python --version: 3.10.6
 - norminette -v: 3.3.52

**Additional context**

**Comment by matthieu42Network** [comment]
Hello, can you provide some code for example? I try with:
```
/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   test.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: root <root@student.42.fr>                  +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/06/23 16:44:52 by root              #+#    #+#             */
/*   Updated: 2023/06/23 16:48:13 by root             ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include<unistd.h>

int	main(void)
{
	return (0);
}
```
and got no error.
