### ISSUE TITLE
Unexpected error in label statements

### ISSUE THREAD

**Issue by NiumXp** [42School/norminette#387]
**Describe the bug**
If we write additional code after a label statement that contains a newline, norminette will stop with an unexpected error.

**Erroneous code**
```c
void	x(void)
{
	start : printf(
		"Hello!");
}
```
```
test.c: Error!
        Error: Unrecognized line (16, 1) while parsing line [<TAB>, <TAB>, <STRING="Hello!">, <RPARENTHESIS>]
```

**Additional infos**
 - OS: Ubuntu 22.04.2 LTS
 - python --version: Python 3.10.6
 - norminette -v: norminette 3.3.52

**Additional context**
...

**Comment by Nikoldigital777** [comment]
To resolve this issue, you should ensure that there is no newline immediately after the label statement. Here's the corrected code:

c:

void x(void)
{
    start: printf("Hello!");
}

By removing the newline after the label, the code should pass the Norminette check without any unexpected errors.
