### ISSUE TITLE
No error after NL_AFTER_VAR_DECL

### ISSUE THREAD

**Issue by NiumXp** [42School/norminette#392]
**Describe the bug**
Norminette don't show `NL_AFTER_VAR_DECL` error when var declaration is followed by a `LBRACKET`.

**Erroneous code**
```c
void	test(void)
{
	int	x;
	{
		printf("Ok?");
	}
}

```

**Additional infos**
 - OS: Ubuntu 22.04.2 LTS
 - python --version: Python 3.10.6
 - norminette -v: norminette 3.3.52

**Additional context**
...

**Comment by astahjmo** [comment]
In [3.3.51 Release]( https://github.com/42School/norminette/releases/tag/3.3.51)  this is working!


![image](https://github.com/42School/norminette/assets/49465538/dadabc9f-44d2-42f4-9f5f-76437849ff4f)

 **Additional infos**

- OS: Ubuntu 20.04.3 LTS
- python --version: Python 3.8.10
-  norminette -v: norminette 3.3.51
