### ISSUE TITLE
LINE_TOO_LONG on multiline string.

### ISSUE THREAD

**Issue by Estecka** [42School/norminette#40]
I tried using a noticeably long string in one of my printf, and so inserted a backslash in the middle to spread
 it across two lines :
```
	printf("\nOh noes. I, n°%i, no longer thinks, and therefore, is no more.\
	*dies in philosopher*\n", this->uid);
```
Accounting for the tabulation at the beginning, the first line amounts to 78 characters, but the norminette seems to believe both lines are one :
```
simulation.c: KO!
	LINE_TOO_LONG        (line:  32, col: 115):	line too long
```
115 happens to be close to the the length of both lines combined (first tabulation removed).

Source file: [simulation.c.tar.gz](https://github.com/42School/norminette/files/5966064/simulation.c.tar.gz)

**Comment by Estecka** [comment]
@N0ich What's the status on this issue ? I believe this was erroneously closed.

As of v3.1.0 (0eaa6cff294b97c2fa764e879ccd2025b9b36a01), the provided code still generates he same error.

I don't think this issue is related to #43. 43 is about functions arguments, this one is about string literals. In fact it's possible to reproduce the issue without using the string as a function argument : 

```
void	ft(char *str)
{
	str = "I am such a long string. Ô so long. So very very long.\
	I am most definitely well over 80 characters.";
}
```

**Comment by N0ich** [comment]
Hello,
I apologize, i believe i fixed part of the issue as of yesterday's update, but looking back it's missing something. I'll fix it today, sorry again.
