### ISSUE TITLE
norminette loop bug

### ISSUE THREAD

**Issue by mehrasmeydani** [42School/norminette#401]
**Describe the bug**
While creating a function, if a space is left between the name of the function and the parenthesis, Norminette will run and get stuck in a loop (ctrl + c is needed to break the loop). This bug is avoided by removing the space between the parameters.

**Erroneous code**
![image](https://github.com/42School/norminette/assets/52368993/151af7e6-5f87-4040-9d2f-159ee10fafbf)

**Additional infos**
 - OS: Ubuntu 22.04.2 LTS
 - python --version: 3.11.0
 - norminette -v: 3.3.52

**Additional context**

**Comment by matthieu42Network** [comment]
Hello, can you provide the erroneous code with text and not with an image?

**Comment by matthieu42Network** [comment]
fixed
