### ISSUE TITLE
MISALIGNED_VAR_DECL bug

### ISSUE THREAD

**Issue by mehrasmeydani** [42School/norminette#402]
**Describe the bug**
When defining 2 variables with different Data Types Norminette will not accept the allignment of columns. This bug is avoided by adding a tab after the data type of the first defined variable.

**Erroneous code**
When defining 2 variables with different Data Types Norminette will not accept the allignment of columns. This bug is avoided by adding a tab after the data type of the first defined variable.
 bug:

![image](https://github.com/42School/norminette/assets/52368993/3cd1f3fd-2075-454f-8f17-c31ebf81a79f)

bug avoided:

![image](https://github.com/42School/norminette/assets/52368993/93e90862-6a10-4cee-b99f-3b7bd9ba3a2b)

**Additional infos**
 - OS: ubuntu 22.04.2 LTS
 - python --version: 3.11.0
 - norminette -v: 3.3.52

**Comment by matthieu42Network** [comment]
Hello, your text editor is not configured with a tabulation of 4 characters.
