### ISSUE TITLE
Function Declaration Inside A Function Scope

### ISSUE THREAD

**Issue by yumamur** [42School/norminette#418]
Function declarations inside a function scope confuses Norminette at the curly braces. Resulting in multiple issues against Norme, although it does not return any error.

**Erroneous Code**
```
int     main(void)
{
        int     a;

        int func(void){typedef struct asd{
        char b;
        while (i < 10)
                i++;
        return (15);
}
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
}
```
`$ norminette main.c`
main.c: Error!
Error: INVALID_HEADER       (line:   1, col:   1):      Missing or invalid 42 header

**Additional infos**
 - OS: Kali Linux 2023/2 amd64
 - python --version: 3.11.4
 - norminette -v: 3.3.53

**Comment by matthieu42Network** [comment]
Hello, the code provided does not compile and norminette have undefined behaviour on code that does not compile.

**Comment by yumamur** [comment]
My mistake, I changed the code while editing in comment section. Undermentioned code should provide a sufficient proof:

#include <stdlib.h>
#include <stdio.h>

int	main(void)
{
	int	a;

	int func(void){
	int i = 0;
	while (i < 10)
		i++;
	return (15);
}
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
a = func();
printf("%d\n", a);
}

**Comment by matthieu42Network** [comment]
Hello, this is a bit complicated here, this code compiles with gcc but not with clang, and clang is the reference. So we will ignore this bug for the moment. We will think about it when clang will support this feature.

**Comment by yumamur** [comment]
Thanks for the response, I didn't know that the reference of our projects should be clang.
