### ISSUE TITLE
If the value of the return statement is a value that accessed an element of an array, norm misdetects an error.

### ISSUE THREAD

**Issue by kiokuless** [42School/norminette#423]
**Describe the bug**
SSIA, the following is the executed result

```console
$ norminette tests/rules/samples/ok_return_value_is_arr_accessed.c
tests/rules/samples/ok_return_value_is_arr_accessed.c: Error!
Error: RETURN_PARENTHESIS   (line:  18, col:  13):      Return value must be in parenthesis
```

**Erroneous code**
```c
/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ok_return_value_is_arr_accessed.c                  :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: kiokuless <kiokuless@example.com>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/08/14 22:47:58 by kiokuless         #+#    #+#             */
/*   Updated: 2023/08/14 22:47:58 by kiokuless        ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

int	f(void)
{
	int	arr[1];

	arr[0] = 1;
	return (arr[0]);
}
```

**Additional infos**
 - OS: macOS Ventura
 - python --version: 3.10.9
 - norminette -v:3.3.53

**Additional context**
Related: #288

**Comment by kiokuless** [comment]
I talked to my friend and it seemed to work in his environment. norminette version is the same, but OS and Python versions are different. I may be mistaken and will look into this a little more closely.

**Comment by NiumXp** [comment]
> I talked to my friend and it seemed to no misdetection in his environment. norminette version is the same, but OS and Python versions are different. I may be mistaken and will look into this a little more closely.

What about `norminette --version` showing Python and OS information to help get that information accurately?

**Comment by kiokuless** [comment]
OS: Debian11 (devcontainer)
python --version: 3.9.2
norminette -v: 3.3.53

As I was creating and testing the devcontainer environment, I could not reproduce the bug even in my original environment.
It seems that I was probably mistaken, So I am closing this Issue. Thanks for your help!
