### ISSUE TITLE
bug on structure control by norminette

### ISSUE THREAD

**Issue by CruorDei** [42School/norminette#436]
**Describe the bug**
When using a while with a single instruction and without brackets, if this instruction is an "if" with its brackets, the norminette returns an error on the opening line of the condition instructions in column 1 ( or there are only tabs).

**Error returned**
Error: MULT_IN_SINGLE_INSTR (line:  XX, col:   1):	Multiple instructions in single line control structure

**Example code triggering the error**
```c
while (++j < size)
			if (tab[i] > tab[j])
			{
				tmp = tab[i];
				tab[i] = tab[j];
				tab[j] = tmp;
			}
```
the error appears on line 3 of this example

![Screenshot from 2023-09-21 16-49-00](https://github.com/42School/norminette/assets/102579154/7588922b-c966-46bc-bba5-df8cb6250060)

**Comment by matthieu42Network** [comment]
Hello, I don't think there is a bug here.
When using a single-line control block, all of your following control blocks must be single lines.
Maybe the error is not clear enough. 

What you need to do is:
```c
while (++j < size)
{
	if (tab[i] > tab[j])
	{
		tmp = tab[i];
		tab[i] = tab[j];
		tab[j] = tmp;
	}
}
```
