### ISSUE TITLE
Union/Struct/Enum Definitions Inside a Function Scope

### ISSUE THREAD

**Issue by yumamur** [42School/norminette#437]
Well, that one is a bit complicated in the context of the Norm.

```
enum e_endian
{
	LITTLE,
	BIG
};

enum e_endian	which_endian(void)
{
	union
	{
		unsigned char	var2[2];
		unsigned short	var1;
	}	u_endian;// This should be the correct indentation
//	}					u_endian; 
	u_endian.var1 = 1;
	if (u_endian.var1 == u_endian.var2[0])
		return (LITTLE);
	else
		return (BIG);
}
```

I assume that the indentation and the alignment of the union should be as it is. Not sure of it's name's though.
It returns many errors, and a variable scope inside a function breaks norminette.

**Comment by matthieu42Network** [comment]
Hello, union is not allowed inside the scope of the fonction, but it needs to return a clear error.

**Comment by yumamur** [comment]
I forgot about that, thanks.
