### ISSUE TITLE
Impossible to use in MacOS 10.13.6 after intallation.

### ISSUE THREAD

**Issue by sargarse** [42School/norminette#440]
**Describe the bug**
I install norminette using the commands provided, but when I run it within the corresponding directory the following message appears: -bash: norminette: command not found.

**Additional infos**
 - OS: 10.13.6
 - python3 --version: 3.10.4
 - norminette -v:

**Comment by Sasha1022** [comment]
Hi,

I had the same issue, it's probaly because you didn't make an alias for it.
If you try with python3 -m norminette
it should work.
Now to make an alias you have to add this line
alias norminette='python3 -m norminette'
at the bottom of the .bashrc file that is in your home directory

**Comment by sargarse** [comment]
Hi,

Norminette works now! I have created the alias in .zshrc, I did not find .bashrc, but I think the two files are the same.
Maybe the problem I have with Francinette is similar.

Thank you so much, I have lost days trying things.

Cheers.
