### ISSUE TITLE
Inconsistent norm operand parsing

### ISSUE THREAD

**Issue by SirMorfield** [42School/norminette#47]
The code
```c
if (p.x < cy.origin.x + cy.radius &&
	p.x > cy.origin.x - cy.radius)
{
	foo();
}
```
gives the errors:
```
test.c: KO!
        SPC_AFTER_OPERATOR   (line:  28, col:  39):     missing space after operator
        EOL_OPERATOR         (line:  28, col:  39):     Logic operator at the end of line
```
However if we change the location of the `&&`:
```c
if (p.x < cy.origin.x + cy.radius
	&& p.x > cy.origin.x - cy.radius)
{
	foo();
}
```
Gives no errors

This is invalid since the Norm V3 says:
`• Each operator or operand must be separated by one - and only one - space.`
In neither of these examples the `&&` operator is separated by `one - and only one - space`
- In the first example the `&&` is separated by first a space and second a newline.
- In the second example the `&&` is separated by first: a newline and a tab and second a space.

Either both or none of the two examples should be allowed.

**Comment by N0ich** [comment]
Hello, as written in the norm:
`Operators must be at the beginning of a line.`
The error exists only to prevent operators at the end of line, and is pretty explicit as well as written in the norm.
