### ISSUE TITLE
Unexpected "Invalid file argument for #include directive"

### ISSUE THREAD

**Issue by harsssh** [42School/norminette#470]
**Describe the bug**
The error message "Invalid file argument for #include directive" occurs in code that includes `float.h`.

**Erroneous code**
```c
#include <float.h>

int	main(void)
{
	return (0);
}
```
```bash
$ norminette main.c
main.c: Error!
	Invalid file argument for #include directive
```

**Additional infos**
 - OS: macOS Mojava
 - python3 --version: pip 23.1.2 (python 3.11)
 - norminette -v: norminette 3.3.55

**Additional context**
The error also occurs when the header name contains a type name, as in the case of `#include <int>`.

**Comment by NiumXp** [comment]
This is a TODO marked in the code:
https://github.com/42School/norminette/blob/7de5543e6e7b5f558d2ee5d1189a3d9c139621f2/norminette/rules/is_preprocessor_statement.py#L205

To fix it you can just put `"FLOAT"` and `"INT"` in the following tuple:
https://github.com/42School/norminette/blob/7de5543e6e7b5f558d2ee5d1189a3d9c139621f2/norminette/rules/is_preprocessor_statement.py#L41-L48
