### ISSUE TITLE
Starting line with * requires 2-tab indentation

### ISSUE THREAD

**Issue by SirMorfield** [42School/norminette#48]
This is invalid:
![Screenshot from 2021-02-17 18-10-10](https://user-images.githubusercontent.com/31915428/108240710-640d2100-714b-11eb-9e24-3854c2d58960.png)
With errror:
```
test.c: KO!
        TOO_FEW_TAB          (line:  29, col:   1):     Missing tabs for indent level
```
To get rid of this error the line has to be indented with 2 tabs:
![Screenshot from 2021-02-17 18-07-17](https://user-images.githubusercontent.com/31915428/108240559-417b0800-714b-11eb-9147-94920972dde0.png)

Copy-paste able code:
```c
static bool	intersect_base(t_ray ray, t_vec3 c, double *t, t_cylinder cy)
{
	n.D = - (n.A * (c.x - cy.origin.x) + n.B * (c.y - cy.origin.y) + n.C
		* (c.z - cy.origin.z));
	n.dist = - (n.A * n.p0.x + n.B * n.p0.y + n.C * n.p0.z + n.D)
		/ (n.A * ray.dir.x + n.B * ray.dir.y + n.C * ray.dir.z);
}
```

**Comment by N0ich** [comment]
Hello,

This is expected. You are nested deeper on the 1st line so the indent is longer.
```
static bool	a(void)
{
	toto1 = - (1
			* 1);
	toto2 = - (1)
		/ (1);
}
```
it boils down to this.
