### ISSUE TITLE
Fix Readme for post PEP 668 installation

### ISSUE THREAD

**Issue by alecmalloc** [42School/norminette#485]
Just a heads up, 

most users on a newer system will run into issues using:
python3 -m pip install --upgrade pip setuptools
python3 -m pip install norminette

**syntax post PEP 668 looks like:
sudo apt install python3-setuptools
sudo apt install pipx
pipx install norminette**

If you'd like I can open a PR to add to readme ;)

**Comment by matthieu42Network** [comment]
Hello, We'll be glad if you do a PR for this :)
