### ISSUE TITLE
Amount of tabulations not checked after user defined typedef

### ISSUE THREAD

**Issue by jvsr** [42School/norminette#58]
After a user defined typedef, an unspecified amount of tabulations is allowed.
As long as the line does not reach over 80 characters and declarations are aligned.
Im unsure if this is intentional but it can make for some ugly cases.

**Erroneous code**
Marked as correct by norminette:
```
typedef foo <TAB> <TAB> <TAB> t_bar;
typedef bar <TAB> <TAB> <TAB> t_foo;
```
```
typedef struct s_foo
{
} <TAB> <TAB> <TAB> t_bar;

typedef struct s_bar
{
} <TAB> <TAB> <TAB> <TAB> <TAB> t_foo;
```
Marked as incorrect by norminette:
```
typedef foo <TAB> <TAB> t_bar;
typedef bar <TAB> <TAB> <TAB> t_foo;
```

**Additional infos**
 - OS: OSX 11.1
 - python --version: 3.9.1
 - norminette -v: 3.1.1

**Comment by N0ich** [comment]
Hello,

Thank you for pointing that out.
To some extent, we cannot limit the number of allowed tabs in case of declarations with a long type, followed by a short type.

I can't limit the number of tabs on the first variable either, if it is a short type and needs to be aligned to a longer one below.
I'm kinda out of ideas. It is fine to leave it like that, but it might be better to have some kind of limitation.
I'm open to suggestions.

**Comment by N0ich** [comment]
Closing due to staleness. Will stay as is for now.
