### ISSUE TITLE
Norminette: bad work with asterisk

### ISSUE THREAD

**Issue by enenarealalexnurmi** [42School/norminette#62]
**Describe the bug**
When checking a certain group of files using wildcards (eg. asterisks) among which there are "is not valid C or C header file", then for each such file, the file name is written, which is the last in the group.

**Erroneous code**
Several valid [1.c, 2.c, 3.c] files in a folder [folder], same count [1.o, 2.o, 3.o] and one valid header file [header.h].
$cd folder && norminette *
$1.c: OK!
$header.h is not valid C or C header file
$2.c: OK!
$header.h is not valid C or C header file
$3.c: OK!
$header.h is not valid C or C header file
$header.h: OK!

**Additional infos**
 - OS: macOS Mojave Version: 10.14.6
 - python --version: Python 2.7.16
 - norminette -v: norminette 3.1.1

**Additional context**
There are also inconsistencies in the Norme file (version 3). General example given on page 5 for struct and typedef incorrect for the current check norminette. In the form in which it is presented visually.

<img width="871" alt="Screen Shot 2021-03-02 at 5 24 23 AM" src="https://user-images.githubusercontent.com/63079050/109587163-a5bca500-7b17-11eb-8e6d-861bd7d03514.png">

**Comment by ggjulio** [comment]
Sorry for duplicates, I did not knew that github search for referenced issues from commits across forks.

**Comment by N0ich** [comment]
Fixed by PR from @ggjulio
