### ISSUE TITLE
Bug with const keyword

### ISSUE THREAD

**Issue by clbrunet** [42School/norminette#64]
**Describe the bug**
When const keyword is placed to the right of the type keyword, it launch an norm error.

**Erroneous code**
Prototype :
`int    execute_cmds(t_cmd const *const *cmds, char *envp[]);`
Norm error :
`MISSING_IDENTIFIER   (line:  29, col:  41):	missing type qualifier or identifier in function arguments`

**Additional infos**
 - OS: Ubuntu 20.04.2
 - python3 --version: Python 3.9.0
 - norminette -v: 3.1.0

**Comment by ggjulio** [comment]
You have a syntax error in your protoype.

But it seem to work (v3.1.2):
`int	execute_cmds(t_cmd const *cmds, char *envp[]);`

**Comment by clbrunet** [comment]
> `int execute_cmds(t_cmd const *cmds, char *envp[]);`
But i want a pointer to a constant pointer to a constant t_cmd.
clang and gcc with -Wall -Wextra -Werror does not show any syntax error

**Comment by ggjulio** [comment]
My bad, I through it was a wrong copy paste.

That way ?
`int	execute_cmds(t_cmd *const *const cmds, char *envp[]);`

**Comment by ggjulio** [comment]
```c
const double *const *const cp1 = arr;
//                         ^ cp1 is ...
//                  ^ a const pointer to ...
//           ^ a const pointer to ...
// ^ a const double
```
https://stackoverflow.com/questions/47854238/c-const-double-pointer
