### ISSUE TITLE
TOO_FEW_TAB on assignment but not only single function call

### ISSUE THREAD

**Issue by jesseVDwolf** [42School/norminette#65]
**Describe the bug**
Assigning the return value of a function to a variable, but splitting the function call up into multiple
lines causes TOO_FEW_TAB. Just calling a function using multiple lines doesn't do this.

**Erroneous code**
Generates error TOO_FEW_TAB
```c
scene->mlx_window = mlx_new_window(scene->mlx,
    scene->width,
    scene->height, "MiniRT");
```

Works fine
```c
mlx_put_image_to_window(scene->mlx,
    scene->mlx_window,
    scene->mlx_image.img, 0, 0);
```

**Additional infos**
 - OS: MacOS Mojave 10.14.6
 - python --version: 3.9.0
 - norminette -v: 3.1.2

**Comment by N0ich** [comment]
Hello,
There was an inconsistency somewhere here. I've fixed it and now the proper way to write this is:
```
int	main(void)
{
	scene->mlx_window = mlx_new_window(scene->mlx,
		scene->width,
		scene->height, "MiniRT");
	mlx_put_image_to_window(scene->mlx,
		scene->mlx_window,
		scene->mlx_image.img, 0, 0);
}
```
Thanks for the issue, closing.

**Comment by N0ich** [comment]
Sorry there was a mistake here as well. The idea is that when it's on an assignation, there is one more tab.
I can change this behavior based on feedback but that was what was required initially.
