### ISSUE TITLE
Norminette doesn't recognize implicit int declaration

### ISSUE THREAD

**Issue by Lylian-Nail** [42School/norminette#78]
**Describe the bug**
Norminette doesn't seem to recognize implicit int declaration.
 
**Erroneous code**
```
char	*ft_strmapi(const char *str, int (*f)(unsigned int, int))
{
	size_t		len = ft_strlen(str);
	char			*dup;
	unsigned 	i;

	i = 0;
	dup = (char *)malloc(sizeof(char) * (len + 1));
```
Generate:
```
NL_AFTER_VAR_DECL    (line:  32, col:   1):     Variable declarations must be followed by a newline
TAB_INSTEAD_SPC      (line:  32, col:  23):     Found tab when expecting space
EMPTY_LINE_FUNCTION  (line:  33, col:   1):     Empty line in function
```
Adding int fix the issue:
```
char	*ft_strmapi(const char *str, int (*f)(unsigned int, int))
{
	size_t		len = ft_strlen(str);
	char			*dup;
	unsigned int	i;

	i = 0;
	dup = (char *)malloc(sizeof(char) * (len + 1));
```
Generates no error.

**Additional infos**
 -  Use docker image generate from Dockerfile
 - norminette -v: 3.1.3

**Comment by N0ich** [comment]
I dont think implicit declarations are expected with the norminette. Can you elaborate?

**Comment by Lylian-Nail** [comment]
It was'nt specified in this and old subjects that implicit declaration was forbidden. In fact I had no issue with this in old norminette (v2).
If it's forbidden it have to be clearly specified in the norminette rules and the errors must be explicit about it.

**Comment by N0ich** [comment]
Thank you. I will look into it.
