### ISSUE TITLE
EMPTY_LINE_FUNCTION between variable assignation and while loop

### ISSUE THREAD

**Issue by celo404** [42School/norminette#80]
**Describe the bug**
When I add an empty line between a variable assignation and a while loop, i got EMPTY_LINE_FUNCTION but I didn't
see any forbidding in the version 2.0.2 of the norme... Did I miss something when reading or the norme version is too older ?

**Erroneous code**

```
#include <stdio.h>

int     ft_sum_mult_three_or_five(int multiple)
{
        int     counter;
        int     result;

        counter = 0;
        result = 0;

        while (counter < multiple)
        {
                if (counter % 5 == 0 || counter % 3 == 0)
                {
                        result = result + counter;
                }
                counter++;
        }
        return (result);
}

```

**Additional infos**
 - OS: Ubuntu 20.04.1 LTS
 - python --version: Python 3.8.5
 - norminette -v: norminette 3.1.3

**Additional context**
Sorry if it's not the correct format it's my first bug report, be clement please 😃
(If there is other problem in my report, let me know ...)

**Comment by N0ich** [comment]
Hello and thank you for your report. This is flagged as a norm error and it is normal, the only empty line in a function should be between var declarations and the rest of the function.

I will make sure that the pdf is properly explaining this. Thank for your report.
