### ISSUE TITLE
Cast followed by a reference operator produce an invalid SPC_AFTER_OPERATOR

### ISSUE THREAD

**Issue by lightdiscord** [42School/norminette#86]
**Describe the bug**

When a cast is followed by a reference operator (`&`) it expects it to be followed by a space (which is not consistent with the same code without a cast).

**Erroneous code**

```c
void test(void)
{
    function((void *)&value);
}
```

The code above produce a norm error, it expects `& value` instead of `&value`.
By the way, if no cast is present `&value` works fine.

**Additional infos**
 - OS: NixOS 21.03
 - python --version: 3.9.0a2
 - norminette -v: 3.2.0

**Additional context**

<details>
  <summary>Traceback</summary>
  
```console
$ norminette -dd
lol.c - IsFuncDeclaration In "GlobalScope" from "None" line 1":
                <VOID> <TAB> <IDENTIFIER=f> <LPARENTHESIS> <VOID> <RPARENTHESIS> <NEWLINE>
lol.c - IsBlockStart In "Function" from "GlobalScope" line 2":
                <LBRACE> <NEWLINE>
lol.c - IsFunctionCall In "Function" from "GlobalScope" line 3":
                <TAB> <IDENTIFIER=function> <LPARENTHESIS> <LPARENTHESIS> <VOID> <SPACE> <MULT> <RPARENTHESIS> <BWISE_AND> <IDENTIFIER=value> <RPARENTHESIS> <SEMI_COLON> <NEWLINE>
lol.c - IsBlockEnd In "Function" from "GlobalScope" line 4":
                <RBRACE> <NEWLINE>
lol.c: KO!
        SPC_AFTER_OPERATOR   (line:   3, col:  22):     missing space after operator
```
  
</details>

**Comment by lightdiscord** [comment]
It also happens in structure initalizer, for example the code below is still considered as invalid.

```c
struct my_struct	g_struct = {
	.field = (void *)&value
};
```

@N0ich Should I open another issue ?

**Comment by N0ich** [comment]
reopening this one, thanks
