### ISSUE TITLE
Struct assignments and what counts as multiple assignments on a single line are not consistent

### ISSUE THREAD

**Issue by pajotg** [42School/norminette#89]
**Describe the bug**
you cant use `.r = 1` on assingments since that would count as multiple assignments on a single line, but `r : 1` is fine (but obsolete since GCC 2.5)

**Erroneous code**
for static values, this is giving a OK:
```
static const t_quaternion	quat = {
	.r = 1,
	.i = 0,
	.j = 0,
	.k = 0
};
```
but for assignments this is giving a KO: (indentation also wierd, other issue created for that #88)
```
*result = (t_quaternion)
	{
	.r = 1,
	.i = 0,
	.j = 0,
	.k = 0
	};
```
but then again, these are considered OK, those are definently on the same line
```
static const t_quaternion	quat = {.r = 1, .i = 0, .j = 0, .k = 0};
static const t_quaternion	quat = {r : 1, i : 0, j : 0, k : 0 };
static const t_quaternion	quats[4] = {[0].r = 3, [1].i = 5 };
*result = (t_quaternion){1, 0, 0, 0};
*result = (t_quaternion){r : 1, i : 0, j : 0, k : 0 };
```
side note: number of spaces before the `}` are not checked on the single line assingments

**Additional infos**
 - OS: GNU/Linux
 - python --version: Python 2.7.18 (also have 3.8.5 and 3.9.2)
 - norminette -v: norminette 3.2.1

**Additional context**
Norm error: `MULT_ASSIGN_LINE`

**Comment by N0ich** [comment]
Hello,

This is very interesting, thank you for pointing all that out. I have a basic fix rolled out to prevent this from happening, but I will need to delve deeper as there are a few behaviors that still might not be handled. 
Thanks a bunch for finding that and taking the time to report it.
