### ISSUE TITLE
Casting either string or constant requires space after rparenthesis

### ISSUE THREAD

**Issue by vincentvis** [42School/norminette#91]
**Describe the bug**
Casting something that is not a variable requires a space, where casting a variable doesn't (but it is allowed to have a space)

**Erroneous code**
```c
(int16_t *)"AA"
(int16_t *)25
```

**Additional info**
 - OS: macos 10.14
 - python --version: 3.9.1
 - norminette -v: 3.2.1

**Additional context**
Can get "around" it by either adding a space or brackets:
```c
(int16_t *) "AA"
(int16_t *)("AA")
```
The first one, without space, generates this:
```
<TAB> <IF> <SPACE> <LPARENTHESIS> <LPARENTHESIS> <IDENTIFIER=int16_t> <SPACE> <MULT> <RPARENTHESIS> <STRING="AA"> <RPARENTHESIS> <NEWLINE>
                                                                                                    ^-----------^
```
If this is not a "string" or "constant" but "identifier" it works _without_ a space (or brackets).

**Comment by N0ich** [comment]
Hello,
I think I've incidentally fixed it while working on #86 and #87, as far as I can test it.
Please let me know if the issue persists when I do the next release. Thanks!

**Comment by vincentvis** [comment]
@N0ich 
It sounds very related, but sadly...
I've just updated to 3.2.2 and get exactly the same
`SPC_AFTER_PAR        (line:  64, col:  32):	Missing space after parenthesis (brace/bracket)`

The actual line of code from the project (just for reference, snippets above do the same)
```c
if (((int16_t *)line)[0] == ((int16_t *)"NO")[0] && is_space)
```

---

It btw seems to be inconsistent with wanting a space between `type` and `*`
Maybe this is a separate issue... but seems related to https://github.com/42School/norminette/issues/87
this is fine:
```c
(int16_t*)varname
```
but this complains that it needs a space:
```c
(short*)varname
```
`SPACE_AFTER_KW       (line:  64, col:  23):	Missing space after keyword`

**Comment by N0ich** [comment]
Thank you, i will investigate this further.
This will probably stand for a few days waiting for the next release.
