### ISSUE TITLE
Wrong number of tabs for single line if / else inside single line control structure

### ISSUE THREAD

**Issue by Hellio404** [42School/norminette#97]
**Describe the bug**
norminette required the wrong number of TABs as you can see below on the code, it should not be valid because the 'else' is on the same level as 'while'
**Erroneous code**
Please use markdown to send the code here.
```c
while (i++ < 17)
    if (i % 2)
        printf("not divided by 2\n");
else
    printf("divided by 2\n");
```

**Additional infos**
 - OS: Macos Big Sur 11.2.1
 - python --version: Python 3.8.2
 - norminette -v: norminette 3.2.3

**Additional context**

**Comment by N0ich** [comment]
Hello,
When writing such conditions, the `while` must have braces. No braces is only for conditions with only one condition inside, or a single line.

I understand this is not clear in the norm, i will update the norm for these cases.

Thanks.
